### PR TITLE
allow specifying only one container

### LINKED ISSUE #2116: New container linting causes index-error unless container spreads over 3 lines
### Description of the bug

Reported [on Slack](https://nfcore.slack.com/archives/CE6PELWR4/p1670550343882459):

```py
286 │   │   if l.startswith("container"):                                  │
287 │   │   │   container_section = l + lines[i + 1] + lines[i + 2]        │
288 │   │   │   if container_section.count('"') > 2:                       │

IndexError: list index out of range
```

This assumption works fine for modules that adhere strictly to the nf-core template but if the module has fewer than 3 lines for the `container` directive this will error or perhaps worse capture lines of other directives. 

This affects `local` modules which might feasibly and legitimately have e.g. only a docker 

```
container "my.dockerhub.url/mycontainer:tag"
```

### Command used and terminal output

_No response_

### System information

nf-core toools v2.7

### PR DESCRIPTION
**Pull request by mirpedrol**
Close #2116 

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mashehu — APPROVED** [review]
Should we have a test for this?

**Comment by mirpedrol** [comment]
> ld we have a test for th

Not sure if we need a test for that, the issue was mainly that I didn't have into account that someone can specify a container in a different syntax than the nf-core modules template 😓

**Comment by awgymer** [comment]
LGTM but have any of us actually tested it on a previously non-compliant but acceptable module?

**Comment by mirpedrol** [comment]
> LGTM but have any of us actually tested it on a previously non-compliant but acceptable module?

I tested one of the modules that only has one container, `container "<URL>"`. This will pass the linting as long as there are <= 2 double quotes. It checks separately the lines that contain docker and singularity containers. If you can think of other formats, we should also test it :)

**Comment by awgymer** [comment]
Only thing I can think of is what happens if the image names are really short and the docker/singularity are on the same line? Actually I think in that case we end up assuming there is only one container per-line and that the line starts with the url 😕
At the least we probably need to document that style if it's (semi?) required.

**Comment by maxulysse** [comment]
you can check the deepvariant modules or the gatk4/cnnscorevariants that use only one container and no conda is available

**Comment by mirpedrol** [comment]
> you can check the deepvariant modules or the gatk4/cnnscorevariants

Works for this type of modules 👍 

> what happens if the image names are really short and the docker/singularity are on the same line?

In that case, it will check the number of double quotes, but only try to connect to the first container it finds. If a module is created with nf-core, even if the containers are short, they will be in two separate lines. For local modules, I will add a warning checking that.

**Pull request merged**
