### PR TITLE
add `--dir/-d` option to schema commands

### LINKED ISSUE #3234: `--dir / -d` argument not available for `pipeplines schema lint, validate, docs`
Hello,

I noticed that only some of the commands in `nf-core tools pipelines schema` accept `--dir/-d`.

Here is an of pipelines commands and if they take `--dir`

| Command | `--dir` |
| ---  |  --- |
| `nf-core pipelines create` | No |
| `nf-core pipelines lint` | Yes |
| `nf-core pipelines schema build` | Yes |
| `nf-core pipelines schema lint` | No |
| `nf-core pipelines schema validate` | No |
| `nf-core pipelines schema docs` | No |
| `nf-core pipelines sync` | Yes |
| `nf-core pipelines bump-version` | Yes |
| `nf-core pipelines create-logo ` | Yes |

I guess it would be nice to be able to use `-d` with all schema subcommands.

### PR DESCRIPTION
**Pull request by mashehu**
Fixes #3234 
not sure if we want it also in `pipelines create`

### CODE REVIEW

**Comment by mirpedrol** [comment]
We already have the option for `pipelines create`, but on the CLI is called `--outdir`/`-o`, we could rename it or better, allow both notations.
image

**Comment by mashehu** [comment]
yeah, was actually thinking the same.

**Comment by nschan** [comment]
Personally, I think -o for create is reasonable. I understand -d to mean "run inside dir" whereas -o is output.

**Review by mirpedrol — APPROVED** [review]
LGTM

**Pull request merged**
