### PR TITLE
refactor: enhance sample checking script

### PR DESCRIPTION
**Pull request by Midnighter**
With this PR I propose to make the following changes as briefly mentioned on Slack.

* `csv.Sniffer` should allow most tabular inputs but writes CSV as nf-core pipelines expect
* refactor validations into checker class
* relax accepted sequence file formats, as mentioned, this is easily changed by modifying

    ```py
    VALID_FORMATS = (
        ".fq",
        ".fastq",
        ".fq.gz",
        ".fastq.gz",
    )
    ```

    in the `RowChecker` class. I like uncompressed formats for local pipelines with many small steps where de-/compression takes up the majority of time.

I will adjust documentation and tests when you have told me exactly what the desired behavior is.

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by drpatelh** [comment]
Need to get the tests passing too.

**Comment by ewels** [comment]
Tests should be passing on `dev` now so if you pull in upstream changes hopefully it'll go all green...

**Comment by Midnighter** [comment]
Alright, I'm happy to update the branch. What about @drpatelh's reservations, though, and I know that @jfy133 had similar thoughts.

> My only slight reservation is that it may be a little tricky for the more novice Python users to figure out what is going on, especially since this will be rolled out to all nf-core pipelines (and newly created ones).

I can add more docstrings if that will help.

**Comment by ewels** [comment]
> I can add more docstrings if that will help.

More docstrings (and docs..) _always_ help 😅

**Comment by Midnighter** [comment]
Alright @ewels, I'm happy with the current state.

**Pull request merged**
