### PR TITLE
Changed default container tag from latest to dev

### PR DESCRIPTION
**Pull request by drpatelh**
Many thanks to contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [X] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [X] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

Changed `container` tag in `nextflow.config` from `latest` to `dev`. This will help with local testing as it ensures that the `dev` docker build is now pulled by default.

### CODE REVIEW

**Comment by drpatelh** [comment]
I made a good guess as to what to change in the helper scripts. Any comments welcome.

**Comment by ewels** [comment]
It's a good start, but still missing quite a few files: see a [repo search for `latest`](https://github.com/nf-core/tools/search?q=%22%3Alatest%22&unscoped_q=%22%3Alatest%22)

**Comment by drpatelh** [comment]
Tests are passing now but I had to change this line in `.travis.yml`:
- docker tag {{ cookiecutter.name_docker }}:dev {{ cookiecutter.name_docker }}:latest

to 
- docker tag {{ cookiecutter.name_docker }}:dev {{ cookiecutter.name_docker }}:dev

Im not entirely sure whether it makes sense to use the same image name with the docker tag command. If not Id imagine the `check_ci_config` function in `lint.py` will have to be stripped down.

**Comment by ewels** [comment]
There's no need to relabel the image `dev` as `dev` - we can just delete that line in the travis config.

You'll probably need to update the linting and python tests to accommodate that change though. Also the lint error docs. This is the problem with having a frameworks 😅

**Comment by drpatelh** [comment]
I thought something was fishy when I looked at the `.travis.yml` for the minimal working example because it was relabelling `dev` to `0.4`.

So keep the line:

docker tag {{ cookiecutter.name_docker }}:dev {{ cookiecutter.name_docker }}:dev

and revert everything back to that commit? 

Need to work out how to revert now!

**Comment by drpatelh** [comment]
No probs. Should be ready to merge now.

**Pull request merged**
