### PR TITLE
add flagg limit_output for modules update

### LINKED ISSUE #3045: Add flag to limit diff output of modules update
### Description of feature

Currently, `modules update` prints a lot of differences including those of nf-test which is not always needed. 
Could it be possible to add a flag that limits this to only the output of the `main.nf` file?

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist
Fixes #3045 
- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mashehu — COMMENTED** [review]
Could you write a quick test for this as well?

**Comment by mirpedrol** [comment]
@nf-core-bot fix linting please!

**Comment by mashehu** [comment]
sorry for messing with your code. I thought I would just polish it a bit, but seems like I created a bit of a mess. working on it.

**Comment by Joon-Klaps** [comment]
> sorry for messing with your code. I thought I would just polish it a bit, but seems like I created a bit of a mess. working on it.

No worries, was procastenating as the testing part was still a bit unclear on how I should approach it so feel free to finish it 😄

**Comment by mirpedrol** [comment]
@nf-core-bot fix linting

**Review by mirpedrol — APPROVED** [review]
Thanks for this PR! LGTM :) 
I have modified the tests a little bit to reduce the code.
1. Using the `caplog` pytest fixture to capture the log messages
2. Removing checks that are covered by other tests, such as assessing if a module was properly updated
3. Since we know which files are modified when we update the modules and subworkflows, we can assess for the specific logging messages directly.

**Pull request merged**
