### PR TITLE
Strip hyphens from hashtags for mastodon compatibiluty

### PR DESCRIPTION
**Pull request by jfy133**
## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mirpedrol — APPROVED** [review]
LGTM!

could you update the CHANGELOG.md? The bot is failing because we modified the structure, so it's not automated now

**Review by mashehu — APPROVED** [review]

**Comment by jfy133** [comment]
Done, I hope that's OK @mirpedrol !

**Review by mirpedrol — APPROVED** [review]
thanks!

**Comment by jfy133** [comment]
@mirpedrol can I do anything to fix the tests or can I ignore?

**Comment by mirpedrol** [comment]
I will have a look! Sorry I didn't notice there were failing tests

**Pull request merged**
