### PR TITLE
Fix multiqc in template

### PR DESCRIPTION
**Pull request by ggabernet**
I've tested creating a template from `nf-core/tools` `dev` and running it and the MultiQC execution didn't work, the MultiQC process was just not executed. This should introduce a fix for it.

I'm also puzzled why then the test `Create a pipeline and test it` worked, as there was also another issue with a variable name

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
> I'm also puzzled why then the test `Create a pipeline and test it` worked, as there was also another issue with a variable name

Somewhat ironically, that CI test is now failing 😅 

```
No such variable: text

 -- Check script 'nf-core-testpipeline/./workflows/testpipeline.nf' at line: 94 or see '.nextflow.log' file for more details
```

**Comment by ggabernet** [comment]
yes I'm investigating that now

**Comment by ewels** [comment]
Yeah, looks like the latest tests on `dev` weren't running MultiQC as you say:

https://github.com/nf-core/tools/actions/runs/3163354597/jobs/5150834572
```
[54/5031c7] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test_illumina_amplicon.csv)
[bf/f50a25] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:FASTQC (SAMPLE2_PE_T1)
[11/8e0260] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:FASTQC (SAMPLE1_PE_T1)
[52/986799] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:FASTQC (SAMPLE3_SE_T1)
[24/a92aa8] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:FASTQC (SAMPLE3_SE_T2)
[21/3ec66f] Submitted process > NFCORE_TESTPIPELINE:TESTPIPELINE:CUSTOM_DUMPSOFTWAREVERSIONS (1)
-[nf-core/testpipeline] Pipeline completed successfully-
```

**Comment by ggabernet** [comment]
yes now the tests pass again but `multiqc` is not being run

**Comment by ggabernet** [comment]
Now it works for me 👍

**Review by jfy133 — APPROVED** [review]

**Review by ewels — APPROVED** [review]
LGTM 👍🏻

Just needs a changelog entry..

**Pull request merged**
