### PR TITLE
New CLI tool: nf-core launch

### PR DESCRIPTION
**Pull request by ewels**
Continuation of #174 on a branch for group-work on the code.

---

New subcommand to interactively prompt the user to set workflow flags before launching.

For example:

```
$  nf-core launch methylseq

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'


INFO: Launching nf-core/methylseq


INFO: Main nextflow options:

Config profile to use [standard]:
Unique name for this nextflow run [False]: Phil's test run
Work directory for intermediate files [work]:
Resume a previous workflow run [False]: true
Release / revision to use [False]: 1.0

INFO: Pipeline specific parameters:

--mindepth [0]:
--nodedup [false]: true
--reads ['data/*_R{1,2}.fastq.gz']:
--numMismatches [0.6]:
--igenomes_base ['s3://ngi-igenomes/igenomes/']:
--container ['nfcore/methylseq:1.0']:
--notrim [false]: false
--max_memory ['128 GB']: 64 GB
--version ['1.0']:
--saveReference [false]:
--unmapped [false]: false
--max_cpus [16]:
--saveTrimmed [false]:
--non_directional [false]:
--comprehensive [false]:
--aligner ['bismark']:
--outdir ['./results']:
--relaxMismatches [false]:
--singleEnd [false]:
--saveAlignedIntermediates [false]:
--nf_required_version ['0.27.6']:
--ignoreFlags [false]:
--max_time ['10d']:
--multiqc_config ['/Users/ewels/.nextflow/assets/nf-core/methylseq/conf/multiqc_config.yaml']:

INFO: Nextflow command:
  nextflow run nf-core/methylseq -name "Phil's test run" -resume -r "1.0" --nodedup --max_memory "64 GB"


Do you want to run this command now? [y/N]: y

INFO: Launching!
```

This is a WIP - need to fill in the PR checklist still. It's a little crude, so any feedback welcome!

NB:  This only works with local paths or workflows that have already been pulled (see https://github.com/nextflow-io/nextflow/issues/889). For anything else, it does not ask for any `params` and just builds the basic command. This should probably be handled in a better way (a warning at least).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging 46fc0a736b6496cb7c15a646dc38c58aa53f929e into 54e233a4c167f515b6f616b3c5a8a9bd660861c0 - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-7e3dd4ff66acf19df3871e42e2736dca25fd1250)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging a79cbb08ede5f9419ede75e03d5cf1ad4096687c into 54e233a4c167f515b6f616b3c5a8a9bd660861c0 - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-796f9856c5b131ba662a4c627c3d2f6cbec08f95)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging a79cbb08ede5f9419ede75e03d5cf1ad4096687c into d0bc828764d7214d48964327ef431a54156b87a1 - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-be003ed730e614ae82be669435697e95a42ba832)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging 183ff79b7881546d01c284a90b27ff310169bfb8 into fe5465c336d87f7903813899654e0a25f3cffd04 - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-89ffc61f5d04aaa46ec2fbaf83ef842f8a545f6a)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging 5361dd6af204f28cb01646c91089110a66a92856 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-313ba86d8c5c8a06dde61ea6d0a89741d7a49211)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging baeb5f8a6e8eb2b97fb538b98a9a9dd636984508 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-78e3a608c1def4ad93a9731bef2b7b5a378197e4)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging 5f8b271e93bd7a752d4f47dd13fa41334c278213 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-ae78378f4e6cd551ca5ffc8d5f32f1390135615f)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging af0426646fee2a0accfdf9ba94d46bce99f3cbbd into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-573fc29f5ad2926f39c2b5c7d94213202085d6b4)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging 054179a3b1a2b90f4f8fba14f7c3160579815803 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-65f6e89de2e2412bb02b2cb32f65d07dd929a4a2)

**new alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging b51770a880571a2f252d6ddbf1b070fa0a3bd045 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-bd9fe6900fb0b22af0d200ab1db3e3a82a228fe3)

**new alerts:**

* 1 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 1 alert** when merging 66e13a0f260632e01c8ec3e957be2e8ce5025b50 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-54fa096e1064438875d8f9d0cdb881e469a305e9)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging e2f81805fe811c36fe890ba4055576e807857fe7 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-5b59244c5a0802958cffe0772d2d1b346062fcd0)

**new alerts:**

* 1 for Unused import
* 1 for Module\-level cyclic import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 3 alerts** when merging 78215417c9070ae608c442d63e1649f584412003 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-3ed74c07dea8b76b07689716a3db0b70f94de710)

**new alerts:**

* 2 for Unused import
* 1 for Wrong number of arguments in a call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 3 alerts** when merging 4a96a3eb8574af5c996c74dfa931b754df4d976c into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-6c0cc18e77cfb82e38d5a9e3e7358cb88e302a88)

**new alerts:**

* 2 for Unused import
* 1 for Wrong number of arguments in a call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging 3d6e8a9b8570895ee80017f3b39fd08a89e9ef03 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-5936a32f2d0ded1b2891376c2198fbdf88128bbc)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging 2616b3ecbd0a8c9cebd50aee909745c4f844426e into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-9fcec2e58fae70fe5b3a1b5c6717539b8c1da697)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging d13af25b3b46b27986a510e611ae1cd5b2d10851 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-b79ca1974824fb4d1fc552a1221c4d14e6d68739)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging da62d5c4881c353a7dc81b75ffad94dfee77f342 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-f416b40bd0c5ffd635477e062cc0ae6a03ae91c6)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
I get a circular import error when trying this code:

```python
Traceback (most recent call last):
  File "/Users/ewels/miniconda2/envs/work/bin/nf-core", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/ewels/GitHub/nf-core/tools/scripts/nf-core", line 12, in <module>
    import nf_core.bump_version, nf_core.create, nf_core.download, nf_core.launch, nf_core.licences, nf_core.lint, nf_core.list
  File "/Users/ewels/GitHub/nf-core/tools/nf_core/launch.py", line 12, in <module>
    from nf_core.workflow import parameters as pms
  File "/Users/ewels/GitHub/nf-core/tools/nf_core/workflow/parameters.py", line 7, in <module>
    from nf_core.workflow import validation as vld
  File "/Users/ewels/GitHub/nf-core/tools/nf_core/workflow/validation.py", line 4, in <module>
    from nf_core.workflow import parameters as pms
ImportError: cannot import name parameters
```

`parameters` imports `validation` which tries to import `parameters`..

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging b6f6a3f36ed98f0388c2d460e842f3c541dd1703 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-f733e48ee7499a8f506e6813316f889242c90da9)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging 39b92594f36f6568dd8d5b4134eef6061a3760b5 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-e57770589093b98da263d4baeb46828c8ca3f000)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
This pull request **introduces 2 alerts** when merging aa11d2ea36ff7bff3e8ac3840fe9c5ca6a281706 into c485729b47b5fc70d75fee7675e5411570e9409c - [view on LGTM.com](https://lgtm.com/projects/g/nf-core/tools/rev/pr-33ae1b9e6e3ec8e224fe9c1eed9ed8651c0669e7)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ewels** [comment]
@sven1103 - are we waiting on anything else to go in to this PR now? Can it be merged?

**Comment by sven1103** [comment]
If you are happy, I am happy with it :)

**Comment by ewels** [comment]
yay

**Pull request merged**
