### PR TITLE
Started with implementing unittests for lint

### PR DESCRIPTION
**Pull request by sven1103**
...and fixed one little thing.

### CODE REVIEW

**Comment by ewels** [comment]
Great! Yes I noticed the same config thing but forgot to submit a PR it seems.

Test code for the tests - very meta! ;)

**Comment by sven1103** [comment]
> Test code for the tests - very meta! ;)

Yes, I hope it is ok ... But I think code coverage is important and not a big deal if one does it right from the beginning.

**Comment by ewels** [comment]
Yeah I’m only joking :) I am terrible at writing tests so it’ll be great to learn how to do it properly..

**Comment by sven1103** [comment]
I think this project is going to be fun!

**Pull request merged**
