### PR TITLE
Vscode settings

### PR DESCRIPTION
**Pull request by ewels**
Get https://github.com/nf-core/website/pull/2579 but for pipelines.

Not sure if it's going to cause trouble adding a `.vscode` directory into pipelines? 👀  Happy to have this closed if people are concerned.

### CODE REVIEW

**Comment by ewels** [comment]
@mirpedrol I guess this probably needs to be made skippable etc by the template creation if we decide we want to add it 😬

**Comment by mirpedrol** [comment]
I'm happy that the new test`test_template_customisation_all_files_grouping` is working 😄 telling us that we added a new file to the template which is not skippable.
I would postpone this to 3.1.0

**Comment by mirpedrol** [comment]
@nf-core-bot update snapshots

**Review by mirpedrol — APPROVED** [review]
LGTM, and all tests passing now :)

**Comment by mashehu** [comment]
I will redirect all the editor warriors to you, @ewels

**Comment by mashehu** [comment]
When one runs nextflow run is that file also coming along with the pipeline? Just feels like quite a tiny user group to serve in all pipelines. Mentioning it in the docs should be enough imo

**Pull request merged**
