### PR TITLE
Sync: Try to fix the GitHub abuse mechanism coping code

### PR DESCRIPTION
**Pull request by ewels**
* Fixes main bug that the default value for the Retry-After header was an int and not a str
* Make the default wait random, between 10 - 60 seconds
* Some tweaks, print the headers in more log messages, make them prettier.

Fixes nf-core/tools#970

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Started writing new tests for this but struggled, as if it's working it just sits in a `while` loop forever, trying again and again. Not sure how to test for that behaviour?!

**Comment by KevinMenden** [comment]
Hmm maybe we just set a maximum number of tries instead of a `while True` loop? 

For instance, could say try maximum 10 times and if it didn't work the first 5 times, then wait for 2h or so.
I guess it's fair to assume that if it doesn't work after 10 times and waiting for some hours, it probably never will.
 
We assign random slots to the sync jobs, which we sample uniformly. So we would have slots 5, 10, 15, 20, ... mins after calling the job. This way the jobs should be spread more or less evenly among the time slots and wouldn't run all at once. But maybe that's a bit too complicated and we just try again until it works 😁

**Comment by ewels** [comment]
> We assign random slots to the sync jobs, which we sample uniformly. So we would have slots 5, 10, 15, 20, ... mins after calling the job. This way the jobs should be spread more or less evenly among the time slots and wouldn't run all at once. But maybe that's a bit too complicated and we just try again until it works 😁

That's sort of what I did here, right? Except with a random number of seconds, maximum one minute. I don't expect that we will need such a large delay between calls to be honest - the example in the docs suggests that the header might say to wait 30 seconds. I think that's more the order of magnitude.

The 403 error code is fairly specific and the actions job will eventually time out after 6 hours (??) or so anyway.

**Comment by KevinMenden** [comment]
Hmm yeah you're right probably that's enough 👍 
Ah okay well in that case that other comment doesn't make sense either.  Seems like it should do the trick then.

**Comment by ewels** [comment]
And hopefully GitHub will tell us how long to wait in the return header anyway, which would be the best way to do it. I wasn't able to test that without abusing GitHub myself, so we'll have to just see...

Happy to merge if you can give a ✅ 😄

**Review by KevinMenden — APPROVED** [review]
👌

**Pull request merged**
