### PR TITLE
be compliant with black defaults in the pipeline template

### PR DESCRIPTION
**Pull request by fabianegli**
Fixes https://nfcore.slack.com/archives/CE5LG7WMB/p1661868498109569

This PR prevents the need for a `pyproject.toml` file in the pipeline template.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Thanks for this! The downside of is that the `check_samplesheet.py` script is being heavily edited between basically every release at the moment. So although it fixes the error for now I feel like it'll just be a matter of time until the same thing happens again..

I wonder if getting the linting config to match nf-core/tools as in https://github.com/nf-core/tools/pull/1789 is more sustainable..

**Comment by fabianegli** [comment]
PS: This PR does not prevent the addition of a `pyproject.toml`.

**Comment by ewels** [comment]
Yes all good points 👍🏻 Maybe worth mentioning that this python script will very likely be replaced / removed in the near future (see `#sample-sheets` Slack channel) so I don't think it's worth putting a lot of work into it at this point.

**Comment by fabianegli** [comment]
After skimming through the #sample-sheet channel, I agree, there is no point in putting much effort in this script.

I think the changes in this PR make the code more readable and can be merged, but if this is not desired this PR should be closed.

**Review by ewels — APPROVED** [review]
LGTM. Leaving to @mirpedrol or @mashehu to merge as they have the bigger picture.

**Pull request merged**
