### PR TITLE
[MAINT] fix argument order

### PR DESCRIPTION
**Pull request by fabianegli**
The `yaml.Dumper.increase_indent()` function only has the two arguments `flow` and `indentless`. There's no need for the `*args` and `**kwargs`.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by mirpedrol** [comment]
Hi @fabianegli, is there any advantage to changing the order of these arguments? I am more familiar with the previous order.

**Comment by fabianegli** [comment]
The previous order is very problematic because then the function might not work as intended. See the following examples (`fun1` relates to what this PR currently does and `fun2` to the status quo):

```python
$ python3.8
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def fun1(pos1, *pos, kw1=None, **kw):
...     print(f"{pos1=}, {pos=}, {kw1=}, {kw=}")
... 
>>> def fun2(pos1, kw1=None, *pos, **kw):
...     print(f"{pos1=}, {pos=}, {kw1=}, {kw=}")
... 
>>> fun1("p1", "p2")
pos1='p1', pos=('p2',), kw1=None, kw={}
>>> fun2("p1", "p2")
pos1='p1', pos=(), kw1='p2', kw={}
>>> fun1("p1", "p2", kw1="kw1")
pos1='p1', pos=('p2',), kw1='kw1', kw={}
>>> fun2("p1", "p2", kw1="kw1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fun2() got multiple values for argument 'kw1'
>>> fun1("p1", kw1="kw1", "p2")
  File "<stdin>", line 1
SyntaxError: positional argument follows keyword argument
>>> fun2("p1", kw1="kw1", "p2")
  File "<stdin>", line 1
SyntaxError: positional argument follows keyword argument
```

Note that providing positional arguments is only possible before any keyword arguments and if tried otherwise it will be a "SyntaxError: positional argument follows keyword argument".

The call to `fun2` resulting in a TypeError is a case where it becomes immediately obvious that the second argument is automatically parsed as the keyword argument at the second position of the function definition. So you can do that, but it won't produce the result you were probably expecting.

**Comment by fabianegli** [comment]
But looking at the code again, I see the `*args, **kwargs` keywords are never used. So this needs some more work.

**Comment by fabianegli** [comment]
`*args` and `**kwargs` are unnecessary and have been removed.

Ready for review.

**Comment by fabianegli** [comment]
Reason for the removal is now given in the OP: "The `yaml.Dumper.increase_indent()` function only hass the two arguments `flow` and `indentless`."

**Review by mirpedrol — APPROVED** [review]

**Pull request merged**
