### PR TITLE
add conda channel order to `nextflow.config` template

### PR DESCRIPTION
**Pull request by mashehu**
On hold until https://github.com/nextflow-io/nextflow/pull/3435 is released

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]
LGTM

**Comment by maxulysse** [comment]
@mashehu https://github.com/nextflow-io/nextflow/releases/tag/v22.10.7

**Comment by maxulysse** [comment]
Nevermind, I think it was merged in https://github.com/nextflow-io/nextflow/releases/tag/v22.11.1-edge.
So pretty sure it's not included in `22.10.7`

**Comment by mashehu** [comment]
This is now available in nextflow >= 23.04, which is the minimum version in the template

**Review by mirpedrol — APPROVED** [review]

**Comment by mashehu** [comment]
@nf-core-bot changelog Template: add conda channel order to nextflow.config

**Pull request merged**
