### PR TITLE
Install tools in the GitPod Docker from the repo itself

### PR DESCRIPTION
**Pull request by JoseEspinosa**
As discussed on Slack copy the repo content in the Docker image and avoid the installation of tools from conda

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated

### CODE REVIEW

**Review by ewels — APPROVED** [review]

**Comment by mahesh-panchal** [comment]
I just saw this. The nf-core is installed from conda because it's needed in other repositories, not just tools.

**Comment by mashehu** [comment]
but the docker file is built in the tools repo, no?

**Comment by mahesh-panchal** [comment]
Ah, yes. OK. Now I understand.

**Comment by mahesh-panchal** [comment]
Hmm. But the update didn't trigger the build. Just now, when I opened the image on modules, it was using nf-core 2.2

**Comment by mashehu** [comment]
Thinking about it. I think we need now to add tags to the gitpod dockerimage, otherwise the dev version (which would be the latest) will be used in all pipeline repos. I tested it in this PR and got 2.4dev for `nf-core --version`.

**Comment by ewels** [comment]
Yeah, we should extend the `push_dockerhub_dev.yml` and `push_dockerhub_release.yml` workflows to handle this image as well.

Note that there was an automated build set up on DockerHub that I found after the release which I deleted, that might be why there is no 2.3 version available? It seemed to be broken (see failing CI on tools `master` branch latest commit) and I thought duplicated. But maybe it wasn't duplicated..? I posted about it on Slack [here](https://nfcore.slack.com/archives/CE5LG7WMB/p1647379923850669).

**Pull request merged**
