### PR TITLE
Fix workflow.onComplete() in template

### PR DESCRIPTION
**Pull request by apeltzer**
PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by ewels** [comment]
What's the story behind this one..? 😕

**Comment by apeltzer** [comment]
The story behind this one was that the variable `workflow.stats.ignoredCountFmt` was the wrong one to look after when sending a "workflow fine" message in the end of each workflow execution. It simply stated "some processes errored" even if there weren't any failing & being ignored.

Therefore this was corrected to the actual `workflow.stats.ignoredCount` variable that actually describes what we want - if there was a process failing and set to ignored this is now flagged in the final output on the log.

**Comment by drpatelh** [comment]
I swear I fixed this in the template too :confused:

**Comment by drpatelh** [comment]
https://github.com/nf-core/tools/pull/337

**Comment by drpatelh** [comment]
What is going on?

**Comment by ewels** [comment]
The merge commit from #337 is not in the commit history of this repo - it must have been reverted at some point?

**Comment by drpatelh** [comment]
image

**Comment by apeltzer** [comment]
Now I'm confused too 😕

**Comment by ewels** [comment]
Oh sorry - I searched for it and got nothing, I didn't look in the history like that. I also did a blame view on the line and got nothing. Ok then I have no idea...

**Pull request merged**
