### PR TITLE
Deal with authentication with private repositories

### LINKED ISSUE #1306: auth problems with private modules repositories
## Description of the bug

Dear developers,

I'm not sure if you plan to fully support this feature, but I found that using *nf-core tools* with private repositories (or even with public branches) has some issues when accessing modules outside from `nf-core/modules`.

## Steps to reproduce

Each of the following command lines have issues with other repositories than `nf-core/modules`:

```bash
nf-core modules --github-repository <a repository> --branch <a branch> list remote
nf-core modules --github-repository <a repository> --branch <a branch> --dir . <a module>
nf-core modules list local # after installing private modules
nf-core modules --github-repository <a repository> --branch <a branch> update <a module>
```

## Expected behaviour

*nf-core tool* lets to specify different repositories and branches with ``--github-repository`` and ``--branch`` options, and the ``modules.json`` has keys to model different repositories and *SHA* than the standard ``nf-core/modules``. Some requests methods to the github API already provide authentication with `auth=nf_core.utils.github_api_auto_auth()`, so the required paches are not so complex as we could expect.

## System

- Hardware:  Desktop
- Executor:  Local
- OS:  Debian Buster
- Version of nf-core/tools:  2.2.dev0
- Python version:  3.9.7

## Nextflow Installation

- Version:  21.04.3 build 5560

## Additional context

I can open a PR in which I had fixed such issues, however this context is difficult to test: should I prove that those patches works in your CI system? Should I need to mock up the API requests (and reponses)?

### PR DESCRIPTION
**Pull request by bunop**
Dear developers,

this PR could close #1306 since is an attempt to solve issues related with authentication with private repositories. However, I'm not sure if I need to prove this within your CI system, for the moment I simply open this and I will wait for your comments

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by grst** [comment]
This looks great, but could you add documentation somewhere how to actually use this? I mean, how would I pass my PAT/credentials to the nf-core command?

**Comment by bunop** [comment]
Happy to contribute. Currently, there are no such information on *tools* documentation. I learn how to do it by seeing the code: there's `nf_core.utils.github_api_auto_auth()` function which read the content of `~/.config/gh/hosts.yml` in order to acquire credentials, so you need to install and configure [github CLI](https://cli.github.com/). After, *nf-core/tool* will be able to list and install private modules.

I wrote some docs for my colleagues on how to work with private repositories, here's [how to set up credentials](https://bioinfo-guidelines.readthedocs.io/en/latest/nextflow/getting-started.html#access-to-private-repositories) and how to [install private modules](https://bioinfo-guidelines.readthedocs.io/en/latest/nextflow/customize.html#custom-pipeline-modules). The command I use are already implemented in *tools* (see `nf-core modules --help` fore more info). You can try to read them and give me feedback. Then I could help you to document the *nf-core/tools* official documentation. I tested this stuff with private modules and branches

**Comment by grst** [comment]
You "how to set-up credentials"-section is really nice. I think around here would be a good place to add it: 

https://github.com/nf-core/tools/blob/5bb9bcaed954cb805f382c764ac4a47f60c68611/README.md?plain=1#L905-L908

**Comment by bunop** [comment]
So, should I add a section on private repository below that section and push such commit?

**Comment by grst** [comment]
that would be awesome :)

**Review by grst — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
