### PR TITLE
Small descriptions for what each github actions .yml file is doing

### PR DESCRIPTION
**Pull request by jfy133**
Many thanks for contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by jfy133** [comment]
I'm not sure what version the CHANGELOG entry should come under, should this come under a 1.8 point release, or should I switch the to merge into master?

**Comment by MaxUlysse** [comment]
I would merge into dev

**Comment by ggabernet** [comment]
yes, exactly, tests are failing cause you are trying to merge to master

**Comment by jfy133** [comment]
Ok I can't get travis to change the branch being pulled into to `dev` despite @ggabernet switching it.

Will try closing re-PRing

**Pull request closed without merging**
