### PR TITLE
Fix NXF_VER ci workflows

### PR DESCRIPTION
**Pull request by ggabernet**
Fix tiny bug in Template CI workflow

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by grst** [comment]
This is now part of the matrix and should not be necessary: 

https://github.com/nf-core/tools/blob/f95860dcf31d6137446b1d27978f11c276310041/nf_core/pipeline-template/.github/workflows/ci.yml#L23-L24

**Comment by grst** [comment]
Please reopen if something doesn't work!

**Review by JoseEspinosa — CHANGES_REQUESTED** [review]
We have been actually discussing about it with @drpatelh and @grst and finally left it the way it is since we thought that it will be populated by the new template anyway. If we go for this syntax the pipeline template should be also update accordingly.

**Comment by JoseEspinosa** [comment]
@grst was faster 🚀

**Comment by ggabernet** [comment]
ah yes I see now that this is also part of the matrix now, but it was not working for me when I created the pipeline, the CI tests were failing

**Comment by ewels** [comment]
I think it's just missing a `$` symbol..

**Comment by ggabernet** [comment]
ok will try it with that

**Comment by ewels** [comment]
Ah no, the `$` is before the `raw` block. Wow that's pretty hard to read. Might put in a mini-PR to address that at least..

**Comment by ggabernet** [comment]
ah never mind, I created a new template and now it works, might have had still an older version of nf-core tools `dev`, thanks for reviewing anyways

**Pull request closed without merging**
