### PR TITLE
Issue 420 fix slack link in readme

### PR DESCRIPTION
**Pull request by GeniusStorm**
- [ ] Fixing the broken slack link and pointing it to the correct nfcore slack channel
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by drpatelh** [comment]
@GeniusStorm I changed the base branch to `dev`. Only stable releases on `master` :+1: Minor changes and `CHANGELOG` has been updated so Ill merge. Thank you!

**Comment by GeniusStorm** [comment]
@drpatelh  I read about the dev branch in contributing doc after creating the PR. Thanks for pointing it to dev and merging this.

**Comment by ewels** [comment]
Tests failing 😞 The jinja varaible `{{ cookiecutter.short_name }}` doesn't exist any more on dev.

Bad @drpatelh! 😆

**Comment by drpatelh** [comment]
Oops. Sorry 🤦‍♂

**Comment by drpatelh** [comment]
Do we have an alternative to get the pipeline name as `chipseq`?

**Comment by ewels** [comment]
Yeah, I'll fix it. Hang on..

**Comment by ewels** [comment]
The variable is present in the python code, which I guess is where you got it from @GeniusStorm? But it needs to be passed through to the cookiecutter template to be properly evaluated.

I've done this in #424, should fix the tests all being well.

**Comment by GeniusStorm** [comment]
@ewels  Yes it in one of the python files. Did not know about passing it through the cookie cutter template. Glad that the tests caught it.

**Pull request merged**
