### PR TITLE
Handle dirty local module repos by force checkout of commits and branches if needed

### PR DESCRIPTION
**Pull request by gregorysprenger**
Use a try/except block to catch `GitCommandError` errors when performing `git checkout`, where changes may need to be stashed or force the checkout. This should solve issues similar to #2656 and the need to use `rm -rf ~/.config/nfcore/nf-core/modules/` where the following error is observed:

> GitCommandError: Cmd('git') failed due to: exit code(1)
>   cmdline: git checkout master
>   stderr: 'error: Your local changes to the following files would be overwritten by checkout:

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Comment by mashehu** [comment]
Thanks, that's a great addition, just tried to make it a bit more fail-safe.

@mirpedrol: do you think we should ask first before we overwrite changes?

**Comment by mashehu** [comment]
@nf-core-bot changelog

**Comment by gregorysprenger** [comment]
@mashehu Awesome, thanks! If you all would rather stash the changes and re-checkout, I'm more than happy to make those changes.

**Comment by mashehu** [comment]
A dirty local module repo is usually the result of an error during an installation/update, so nothing could actively be lost, maybe I am just a bit too paranoid... this is probably the better solution, instead of dragging an installation error along

**Comment by mirpedrol** [comment]
Looks good! but I agree with @mashehu I would prefer to first ask the user if they want to continue and delete changes.

**Comment by mashehu** [comment]
after a quick thought, new idea: because we use this function also in other contexts, we should check that we are in the modules repo in the if clause and then do a force checkout with a prompt and otherwise raise an errror to be on the save side

**Pull request merged**
