### PR TITLE
Add Prettier ignore comments

### PR DESCRIPTION
**Pull request by Emiller88**
https://nfcore.slack.com/archives/CE5LG7WMB/p1648742029535629

### CODE REVIEW

**Comment by ewels** [comment]
See slack comment, but I would rather not use `prettier-ignore` as I actively want prettier to parse these files. Ignoring the single lines is fine (not entirely clear how these `prettier-ignore` comments work - do they ignore the rest of the file or just the next line?), but I'm not sure that we need to? The comments I added means that prettier runs fine.

What I was planning on doing was just adding _some_ text on the lines that have a single line `#` character after the template renders. Just so that it doesn't look like a typo.

**Comment by jfy133** [comment]
Also so we don't forget (as discussed on slack)

It would be good to add the following to the template:  https://github.com/nf-core/taxprofiler/blob/dev/.prettierignore

**Comment by ewels** [comment]
> Also so we don't forget (as discussed on slack)
> 
> It would be good to add the following to the template: https://github.com/nf-core/taxprofiler/blob/dev/.prettierignore

@jfy133 done: https://github.com/nf-core/tools/pull/1505 (just after your comment, which I only just read)

@Emiller88 - want to update this PR or should I make a new one?

**Comment by Emiller88** [comment]
@ewels Whatever you want to do!

**Comment by ewels** [comment]
Going for https://github.com/nf-core/tools/pull/1508 instead - hope that's ok!

**Pull request closed without merging**
