### PR TITLE
added NXF_ANSI_LOG variable export to template CI

### PR DESCRIPTION
**Pull request by ggabernet**
Many thanks to contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by apeltzer** [comment]
Might be not needed in upcoming 20.01+ releases: https://github.com/nextflow-io/nextflow/issues/1417 

But nevertheless not bad to have it for earlier versions of Nextflow!

**Comment by ewels** [comment]
Ahh too fast, the proper way to do this is to use `env` scope in GitHub actions - see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#env 

I had thought that env variables were not carried over between steps, which would mean that this doesn't work..? But perhaps that was only jobs. Either way, setting it as a global env variable for the whole workflow should be safer.

**Comment by ewels** [comment]
I think it still will be - sounds like Travis at least tells tools that they are talking to a tty shell so I think Nextflow still won't know that it's running on a environment where line redrawing doesn't work.

**Comment by ggabernet** [comment]
I can still fix this later today with another PR

**Comment by drpatelh** [comment]
I was wondering how the environment variables would be passed amongst the different `run` commands but didn't know enough about it. Good spot :+1:

**Pull request merged**
