### PR TITLE
Use pathlib

### LINKED ISSUE #1527: Consistently using pathlib.Path would simplify a lot of path handling in this codebase
### Description of feature

This repo uses many different ways to handle paths. Plain strings, `os` and pathlib. Currently, most path handling is done with `os.path`. The reason to propose the pathlib.Path option is that it also has the convenient .is_dir, is_file and .glob functions as well as a nice path composition API and even operators.

```
p.absolute(        p.glob(            p.is_reserved(     p.name             p.rename(          p.suffix          
p.anchor           p.group(           p.is_socket(       p.open(            p.replace(         p.suffixes        
p.as_posix(        p.home(            p.is_symlink(      p.owner(           p.resolve(         p.symlink_to(     
p.as_uri(          p.is_absolute(     p.iterdir(         p.parent           p.rglob(           p.touch(          
p.chmod(           p.is_block_device( p.joinpath(        p.parents          p.rmdir(           p.unlink(         
p.cwd(             p.is_char_device(  p.lchmod(          p.parts            p.root             p.with_name(      
p.drive            p.is_dir(          p.lstat(           p.read_bytes(      p.samefile(        p.with_suffix(    
p.exists(          p.is_fifo(         p.match(           p.read_text(       p.stat(            p.write_bytes(    
p.expanduser(      p.is_file(         p.mkdir(           p.relative_to(     p.stem             p.write_text(  
```

Do the gatekeepers have any thoughts about this? Or reasons not to make more use of pathlib?

As an example:
https://github.com/nf-core/tools/blob/e0d00d3e09a996f59eb5ce6ebc4795452a5b1d39/nf_core/modules/nfcore_module.py#L32-L35

If `module_dir` would be a `pathlib.Path` Line 32 to 35 could be a single line:

```python
        self.module_name = module_dir.name
```

This would also solve an unexpected behaviour if the pipeline resides in a nested folder structure, with multiple non-consecutive levels named "modules", `self.module_name` becomes a path. (There are of course solutions to this issue without pathlib.Path, but I think it is one nice example how pathlib.Path can help reduce complexity.)

```python
>>> "modules/path/to/pipeline/modules/name".split("modules" + os.sep)[1]
'path/to/pipeline/'
```

### PR DESCRIPTION
**Pull request by fabianegli**
This PR contains the following:

- [ ] migration to pathlib.Path
    - [x] for all tests
    - [ ] for production code
    - [ ] for all click input (-> `type=click.Path(...)`)
- [x] a fix for a duplicated test name
- [x] removal of many unused imports
- [ ] removed deprecated tests tests
- [ ] ... WIP ...

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

Closes #1527

This PR contains quite a lot of changes because there is a big amount of path handling in the code. A considerable amount of that could probably be removed with some refactoring.

### CODE REVIEW

**Comment by fabianegli** [comment]
The tests pass, but i have some reservations that input over click might at some points also need a conversion to Path objects.

**Comment by ErikDanielsson** [comment]
Since this PR will practically touch the entire code base it might make sense to split it into several PR so we can test them all individually.

**Comment by fabianegli** [comment]
I do agree it is developing into a monster PR. But it is not always clear where to draw the lines when making such a migration to also not just make an insane number of PRs ;-) 

I am open to suggestions.

**Comment by ErikDanielsson** [comment]
You could possibly split it so you make one PR for the tests, one for the modules code and one for the non modules code. If you are willing you can split it up further -- the smaller the PRs the better. I would focus on the `pathlib` stuff first also, since keeping it limited to one topic makes it easier to see why a certain change was made.

**Comment by fabianegli** [comment]
I did start with the tests. But when changing the tests to pathlib sometimes it makes a lot of sense to also migrate the code being tested...

**Comment by ErikDanielsson** [comment]
I'm not against in general, as long as you are careful that it does not grow too big

**Comment by fabianegli** [comment]
Closing and cherry-picking into smaller PRs.

**Pull request closed without merging**
