### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by MaxUlysse**
Need 2 spaces to indent, not 1

## PR checklist

 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Realized with #846 that I fixed that in sarek, but not in the template

**Review by ggabernet — APPROVED** [review]
LGTM!

**Comment by ewels** [comment]
I wonder why the markdown linting didn't pick this up 🤔

**Comment by MaxUlysse** [comment]
same

**Pull request merged**
