### PR TITLE
update json-schema template to new structure

### PR DESCRIPTION
**Pull request by mashehu**
First try at #687 
Not sure if we really need to ditch `type:object`for groups as done in the example, because they still contain properties. This would also mean less changes in the other code (which often identifies a group by `type==object`). But maybe I misunderstood the changes for the new structure. 🤷‍♂️

### CODE REVIEW

**Comment by ewels** [comment]
_Note to self: diff is mostly whitespace, see [diff without whitespace](https://github.com/nf-core/tools/pull/688/files?diff=unified&w=1)_

I don't quite understand your comment - you have ditched the `type:object` in this PR, right? The `definitions` entries can still have their own properties..

**Comment by mashehu** [comment]
no, all elements except for parameters are still all `type:object` as before, including the topmost element with the `definitions`. The latter was in the example you posted, so I left it like that.

**Comment by ewels** [comment]
Yeah, I think that the topmost element needs to be an object. I hadn't noticed that the [`type:object` lines](https://github.com/nf-core/tools/blob/9add5446d9cc8982071e2d60a19de851cb2563c6/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/nextflow_schema.json#L10) were still there in this PR. I think you can just delete them..?

Maybe I should back up and give a proper explanation for why the nasty hack was needed. I'll add a comment with this to #687

**Comment by ewels** [comment]
I was wrong: https://github.com/nf-core/tools/issues/687#issuecomment-663549288

Good to merge ✅  - will do so into a branch so as not to mess up `dev` until we're ready.

Will start working on updating the rest of the code and fixing the tests.

**Pull request merged**
