### PR TITLE
Allow specification of Conda build id as well as version

### PR DESCRIPTION
**Pull request by drpatelh**
Many thanks for contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by drpatelh** [comment]
e.g. if I have `- bioconda::ivar=1.2=h3ae53b1_0` in the environment then the linting fails:

```bash

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

Running pipeline tests  [########################------------]   66%  00:00:04  'check_readme'
ERROR: Found test failures in 'check_conda_env_yaml', halting lint run.


INFO: =============================
          LINTING RESULTS
===================================
  [✔]  123 tests passed
  [!]    9 tests had warnings
  [✗]    1 tests failed

WARNING: Test Warnings:
  http://nf-co.re/errors#4 : Config variable not found: params.single_end
  http://nf-co.re/errors#8 : Conda package is not latest available: conda-forge::python=3.6.10, 3.8.2 available
  http://nf-co.re/errors#8 : Conda package is not latest available: conda-forge::markdown=3.1.1, 3.2.1 available
  http://nf-co.re/errors#8 : Conda package is not latest available: conda-forge::pymdown-extensions=6.0, 7.1 available
  http://nf-co.re/errors#8 : Conda package is not latest available: conda-forge::r-base=3.6.2, 3.6.3 available
  http://nf-co.re/errors#8 : Conda package is not latest available: bioconda::samtools=1.9, 1.10 available
  http://nf-co.re/errors#8 : Conda package is not latest available: bioconda::bowtie2=2.3.5.1, 2.4.1 available
  http://nf-co.re/errors#8 : Conda package is not latest available: bioconda::bcftools=1.9, 1.10.2 available
  http://nf-co.re/errors#8 : Conda package is not latest available: bioconda::unicycler=0.4.7, 0.4.8 available

ERROR: Test Failures:
  http://nf-co.re/errors#8 : Conda dependency did not have pinned version number: bioconda::ivar=1.2=h3ae53b1_0

ERROR: Sorry, some tests failed - exiting with a non-zero error code...
```

**Comment by ewels** [comment]
Weird, I have never seen an ID specified like that. Why would you need it?

**Comment by ewels** [comment]
Would be nice if you could add a new test for this case, but not essential.

**Comment by drpatelh** [comment]
We dont use such notation normally because `<package>=<version>` is enough, however, I had to use `<package>=<version>=<build>` because `iVar` had been updated on Conda and for some reason even if I provided `1.2` as the version to use the package was being resolved to `1.2.1`. The only way around it was to provide the <build> number too :smirk: but that failed the linting. Was quite a fun evening 😅 

If you use `conda env export > environment.yml` the `<package>=<version>=<build>` is normally used when saving/sharing the environment to ensure that you use the same build of packages too for "reproducibility".

Added an example here https://github.com/nf-core/tools/pull/603/commits/58232f84f1da90f0e64444cc8a4ef183f2b0edcc :)

**Comment by drpatelh** [comment]
Added a test and tests are passing @ewels :)

**Pull request merged**
