### PR TITLE
Fix tests after DSL2 v2.0 release of modules

### PR DESCRIPTION
**Pull request by JoseEspinosa**
Draft PR to work together on fixing test after DSL2 v2.0 release of modules

## PR checklist

 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by grst** [comment]
At least locally, all tests are passing now :tada:

**Comment by grst** [comment]
```
Nextflow version 21.09.1-edge does not match workflow required version: >=21.10.3
```
Is that because there's no edge version since the latest stable release?  What do we do? Just comment it out in the CI script?

**Review by drpatelh — APPROVED** [review]
Awesome work guys!

**Comment by drpatelh** [comment]
> Is that because there's no edge version since the latest stable release? What do we do? Just comment it out in the CI script?

Yes let's hop on the call again to discuss this maybe?

**Pull request merged**
