### PR TITLE
Git creates dev now too

### PR DESCRIPTION
**Pull request by apeltzer**
Attempt at addressing #372. Adds in a  `dev` branch when using the `nf-core create` command automatically.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Tests broke because Parameters schema URL is now somewhere else, I updated that in this PR now too and hope that things work now, URL is now:

https://nf-co.re/params/0.2.0dev/parameters.schema.json

**Comment by ewels** [comment]
Ah you beat me to it! Closing https://github.com/nf-core/tools/pull/375 (I was on a plane without internet in fairness)

**Comment by ewels** [comment]
Maybe we should fix the tests first in a separate PR, then have nice clean commit histories here and in #374 ..? 😉

**Comment by apeltzer** [comment]
Closing in favor of #377

**Pull request closed without merging**
