### PR TITLE
Modules: add a panel around diff previews when updating

### LINKED ISSUE #3239: Add a separater between each module's set of diffs during 'preview changes' during module updates
### Description of feature

When I do a mass update of all modules in pipeline using `nf-core modules update`, and I preview each change, the output is very hard to read for where one module's diff starts and ends

![Image](https://github.com/user-attachments/assets/aa7924f4-d3c5-4c00-bb3a-51e0095f760f)

It would be nice to put either a long separator or marker that spans the whole screen so I can better see where each set of files starts/stops

e.g.

```
 +          type: file                                                                                                                                                                                  
 +          description: File containing software versions                                                                                                                                              
 +          pattern: "versions.yml"                                                                                                                                                                     
  authors:                                                                                                                                                                                              
    - "@louperelo"                                                                                                                                                                                      
  maintainers:                                                                                                                                                                                          
                                                                                                                                                                                                        
                                                                                                                                                                                                        
INFO     'modules/nf-core/amplify/predict/main.nf' is unchanged                                                                                                                                         
INFO     'modules/nf-core/amplify/predict/tests/main.nf.test' is unchanged                                                                                                                              
INFO     'modules/nf-core/amplify/predict/tests/tags.yml' is unchanged                                                                                                                                  
INFO     'modules/nf-core/amplify/predict/tests/main.nf.test.snap' is unchanged   
##################################################################################################                                                                                                                      
? Update module 'amplify/predict'? Yes 
INFO     Updating 'nf-core/amplify/predict'                                                                                                                                                             
INFO     Changes in module 'nf-core/amrfinderplus/run' between (c0514dfc403fa97c96f549de6abe99f03c78fe8d) and (666652151335353eef2fcd58880bcef5bc2928e1)                                                
INFO     Changes in 'amrfinderplus/run/environment.yml':                                                                                                                                                
                                                                                                                                                                                                        
 --- modules/nf-core/amrfinderplus/run/environment.yml                                                                                                                                                  
 +++ modules/nf-core/amrfinderplus/run/environment.yml                                                                                                                                                  
 @@ -1,7 +1,5 @@                                                                                                                                                                                        
 -name: amrfinderplus_run                                                                                                                                                                               
  channels:                                                                                                                                                                                             
    - conda-forge                                                                                                                                                                                       
    - bioconda                                                                                                                                                                                          
 -  - defaults                                                                                                                                                                                          
  dependencies:                                                                                                                                                                                         
    - bioconda::ncbi-amrfinderplus=3.12.8                                                                                                                                                               
                                                                                                                                                                                                        
                                                                                                                                                                                                        
INFO     Changes in 'amrfinderplus/run/meta.yml':                                                                                                                                                       
                                                                                                                                                                                                        
 --- modules/nf-core/amrfinderplus/run/meta.yml                              
```

### PR DESCRIPTION
**Pull request by mashehu**
fixes #3239

### CODE REVIEW

**Comment by jfy133** [comment]
Do you have a screnshot as to what it looks like?

**Comment by mashehu** [comment]
https://github.com/nf-core/tools/issues/3239#issuecomment-2434515673

**Review by jfy133 — COMMENTED** [review]
Yes, but it would also be nice to have a marker between each group of files too, e.g. set of files per module.

My reasoning is I need to make sure e.g. I look at the combination of a main.nf and meta to make sure I understand what channel modifications I have to make in the pipeline

**Comment by mashehu** [comment]
okay, a bit more difficult, but I will give it a try

**Comment by jfy133** [comment]
> okay, a bit more difficult, but I will give it a try

Can just be a straight line across the whole width of screen printed before the question of 'updated X/y/z module'?

**Comment by mashehu** [comment]
Screenshot 2024-10-24 at 17 15 40
better?

**Comment by mashehu** [comment]
alternative 2
Screenshot 2024-10-24 at 18 24 59

**Comment by jfy133** [comment]
Yes I think that will do for now (would need to try to test in the wild a few times ).

The blue border is nice but I find it's a hit harder to read the name of the module

But no strong feeling on the colour

**Review by jfy133 — APPROVED** [review]

**Comment by mashehu** [comment]
how about this then
Screenshot 2024-10-25 at 10 42 21

**Review by mirpedrol — APPROVED** [review]
LGTM!

**Pull request merged**
