### PR TITLE
style: yaml => yml

### PR DESCRIPTION
**Pull request by Emiller88**
It's the only `yaml` file in a sea of `yml`

### CODE REVIEW

**Review by grst — APPROVED** [review]
Team `yml` :tada: 

But seriously, does it have any side-effects?

**Comment by ewels** [comment]
MultiQC shouldn't care, it loads both. It may affect template sync stuff maybe? But yeah it's probably fine.

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
@Emiller88 If you fix the tests as well, would be perfect

**Comment by Emiller88** [comment]
@maxulysse Done!

**Pull request merged**
