### PR TITLE
Added a new podman profile

### LINKED ISSUE #742: Add a podman profile to the template
Currently, Nextflow supports Docker, Singularity and Podman as container engines.

However, nf-core projects do not come with a Podman profile, only Docker & Singularity.

I personally consider this to be inconsistent. Podman is shaping up to be a strong Docker alternative and I would like it to be supported first class.

A simple

```
podman {
    podman.enabled = true
}
```

should allow people to run nf-core pipelines also with profile podman.
Don't think we need additional settings here, but I guess this would need some empirical evaluation.

Cheers

### PR DESCRIPTION
**Pull request by Zethson**
Fixed #742

### CODE REVIEW

**Review by apeltzer — APPROVED** [review]
LGTM. We can then nevertheless (and probably should?) test it 👍

**Review by ewels — COMMENTED** [review]
We need to add to the documentation for this as well. The profile names are described in quite a lot of places..

**Comment by Zethson** [comment]
@ewels Guess the documentation issue should be at the website?

If yes I would merge this PR and open a new issue there.

**Comment by ewels** [comment]
Website is the main one, but there is quite a bit in the template readme for example. I guess also the `docs/usage.md`.

**Comment by Zethson** [comment]
@ewels All right.
I will add it as soon as I find the time.

**Comment by MaxUlysse** [comment]
could be worth mentioning in .github/ISSUE_TEMPLATE/bug_report.md too

**Comment by ewels** [comment]
Sorry for being a hassle - it's just easy for new features like this to get lost with lots of contributors and a big changelog :) Thank you!

**Review by ewels — APPROVED** [review]
Let's merge this quickly to get the new functionality before the minor release, and add an issue to add it to the docs.

**Pull request merged**
