### PR TITLE
Patch 1.6.1

### PR DESCRIPTION
**Pull request by sven1103**
Hotfix for the invalid parameter schema URL

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by apeltzer** [comment]
Going straight to `master`therefore TravisCI fails - intended to have a 1.6.1 release before we do the 1.7.0 ?

**Comment by sven1103** [comment]
> Going straight to `master`therefore TravisCI fails - intended to have a 1.6.1 release before we do the 1.7.0 ?

Yes, to roll-out the broken link quickly. That was my intention :)

**Comment by ewels** [comment]
Seeing as we are intending to release v1.7 tomorrow, I'm going to change the base for this PR to `dev`.

We should still allow patch releases, but here I see no reason for it. Feel free to complain if you disagree 😅

**Comment by apeltzer** [comment]
Patch releases will be enabled after #404 is merged in here, so in the future we can do such releases now 👍 

I don't see an issue to have this now in `dev` and fixed in the upcoming release therefore 👍

**Comment by apeltzer** [comment]
(though we can close this now, as it is already contained in the `dev` branch and fixed there!)

**Pull request closed without merging**
