### PR TITLE
feat: add a modules mulled command

### PR DESCRIPTION
**Pull request by Midnighter**
Add a command `nf-core modules mulled` that can generate image names from given tool specifications. See the discussion at https://nfcore.slack.com/archives/C01LNCGJBMH/p1649431242727599

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by Midnighter** [comment]
I don't think that the failing pipeline lint test is my fault.

**Review by JoseEspinosa — COMMENTED** [review]
Very nice @Midnighter!
My only concern is that the hash of the mulled container is generated even if the container is not yet available. I am not aware that this could be checked using the Biocontainers API so maybe we could make a `get` request to the singularity registry and if the status code response is not 200 then print a warning? Or maybe we can just print always a warning that the hash is generated even if the image is not yet available?

**Comment by Midnighter** [comment]
> My only concern is that the hash of the mulled container is generated even if the container is not yet available. I am not aware that this could be checked using the Biocontainers API so maybe we could make a `get` request to the singularity registry and if the status code response is not 200 then print a warning? Or maybe we can just print always a warning that the hash is generated even if the image is not yet available?

That's a fair point. I've been struggling with this as well. My solution would have been to write in the docs that you should use the `mulled-search` to find an image but if you have an entry in the `hash.tsv`, you can use this tool.

**Comment by JoseEspinosa** [comment]
> 

Fair enough :smiley:  let's see what others think

**Comment by Midnighter** [comment]
Please take another look. I'm now polling quay.io for the existence of the image.

**Review by JoseEspinosa — APPROVED** [review]
Just made a small suggestion, it looks great to me now! Thanks @Midnighter :rocket:

**Comment by jfy133** [comment]
Late to the game (sorry have a big backlog) but I think this would be really useful as I had this issue exactly yesterday trying to find something.

Only comments would be:

1. I would expect someone would argue that this is not a nf-core specific tool, more towards biocontainers, so someone may ask to make it standalone
2. I would say `mulled` as a subcommand  alone is rather uninformative. Make `biocontainers-search-mulled` or something would be better (also I would say making the name longer would make it sort of clearer it's less nf-core specific)

**Comment by Midnighter** [comment]
1. Integrating it into the tools was an explicit wish by @ewels and @JoseEspinosa, I don't care myself.
2. I don't have strong feelings regarding the command name, however, I would not name it search because it doesn't search anything. It generates the name by hashing the inputs and then verifies that this name exists.

**Comment by JoseEspinosa** [comment]
Here is the link to the discussion we had for completeness: https://nfcore.slack.com/archives/C01LNCGJBMH/p1649431242727599
1. Maybe we should check what others think?
2. I don't have any strong opinion, I know my limitations and naming commands is not one of my strengths :stuck_out_tongue: But I agree that search is misleading since in fact, the script creates the hash even if the mulled container has not yet been created.

**Comment by ewels** [comment]
I'm happy enough with this, it's a super obscure name but also a pretty obscure function...

This PR is missing any contributions to the docs though! Needs adding to `README.md` at least, with some long-form discussion about what it is and how to use it.

Ideally that would also be complemented with some docs on the website / in the modules readme if possible.

**Pull request merged**
