### PR TITLE
Module linting: Only lint script if there was a script.

### PR DESCRIPTION
**Pull request by ewels**
Basically, skip this step if using shell instead.
Fixes nf-core/tools#1558

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]

**Review by JoseEspinosa — CHANGES_REQUESTED** [review]
Shouldn't we test that the `template` tag is present in the `script:` section to avoid that a module without a template has not `shell` block?

**Comment by ewels** [comment]
I actually started doing this but then stopped as wasn't sure about edge cases - whether `script` blocks should _always_ have a template or not.

But easy to add, I'll do it now.

**Comment by ewels** [comment]
Done 👍🏻

**Comment by ewels** [comment]
@JoseEspinosa - done 👍🏻

**Review by JoseEspinosa — APPROVED** [review]
Awesome @ewels

**Pull request merged**
