### PR TITLE
Comment on PR if branch test fails

### PR DESCRIPTION
**Pull request by ewels**
If the GitHub Actions test for the PR target branch fails, automatically add a comment to the PR explaining what went wrong and how to fix it.

Closes nf-core/tools#558

Also updated variable handling mentioned in nf-core/tools#554

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by ewels** [comment]
Tested on my fork (with some minor changes so that the action would actually run on my fork). See https://github.com/ewels/nf-core-tools/pull/1

**Comment by MaxUlysse** [comment]
That looks amazing.

I'm glad you liked this idea.

The only improvement I can see now, is to remove the patch protection, because I think it's bothersome to name the branch patch.
And add a comment saying that it's OK for a bugfix.

But that could be complicated to phrase or explain properly.

**Comment by ewels** [comment]
https://github.com/ewels/nf-core-tools/pull/1#issuecomment-591952155

> Maybe we just ignore the `patch` thing altogether? It should be pretty rare and people can read about it / ask about it elsewhere..

**Comment by MaxUlysse** [comment]
Good for me.

We can always use our admin privileges to merge PR anyway

**Pull request merged**
