### PR TITLE
[FIX] Schema validation for empty string defaults

### PR DESCRIPTION
**Pull request by jpfeuffer**
sanitise_param_default should probably always return a dict. I tried adding a test but I think adding a full extensive test schema would be better. The template that is tested, is not very complex.

### CODE REVIEW

**Comment by ewels** [comment]
I'm a bit lost to what this code is doing. Why would you ever set a default string of `""`?

If it's related to initialising blank params, https://github.com/nf-core/tools/issues/992 may be related (everything should be initialised as `null`). We will be disallowing empty string defaults very soon I think.

**Comment by jpfeuffer** [comment]
I agree but if you want to completely forbid this, the function should return an error instead of an object that does not fit to the general return type of the function.
Outer functions require it to return a dict.

**Comment by jpfeuffer** [comment]
Or is the empty string considered to be the return type for "Failed"?

**Comment by ewels** [comment]
> I agree but if you want to completely forbid this, the function should return an error instead of an object that does not fit to the general return type of the function.
> 
> Outer functions require it to return a dict.

Yup I completely agree, it definitely sounds like a bug as it stands. I was just thinking that a better fix would be to remove this code completely as part of the bigger issue. I was curious if you were deliberately setting default values like these for a reason that I hadn't thought of.

**Comment by jpfeuffer** [comment]
I see! No not really, I think they were leftovers because we did not know back then that null was possible as a value.
I think it should be fine for us to use null everywhere.

**Review by ewels — APPROVED** [review]
Coming back to this, I agree with the PR. This code is for fetching the values, so it's too early to be making decisions about whether those values are valid or not. That will happen later in the linting code.

**Pull request merged**
