### PR TITLE
Awsbatch trace file sanity

### PR DESCRIPTION
**Pull request by KochTobi**
* prevent tracefiles from being written into `s3` storage

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by KochTobi** [comment]
wrong base branch

**Comment by ewels** [comment]
What was wrong with this sorry? Tests failed because there's no entry to the changelog.

**Comment by KochTobi** [comment]
I extended the master branch instead of the dev branch

**Comment by ewels** [comment]
I don't think that matters. Your target branch is `dev` and the commits you're trying to merge are only the relevant ones.

**Pull request closed without merging**
