### PR TITLE
TEMPLATE: Fix version comment action

### PR DESCRIPTION
**Pull request by mashehu**

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
I came across this issue in 3.0.1 :grimacing:

**Review by maxulysse — CHANGES_REQUESTED** [review]
this is still not working :sob:

**Comment by mirpedrol** [comment]
Looks like there is an error with the action to read the yaml file https://github.com/pietrobolcato/action-read-yaml/issues/14 should we try the fork mentioned in this issue?

**Comment by maxulysse** [comment]
As far as I can tell all PRs once a template sync has been merged ran into this error

**Review by mirpedrol — APPROVED** [review]
Working now 🙂 LGTM!

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
CHANGELOG?

**Pull request merged**
