### PR TITLE
Add charliecloud.registry

### PR DESCRIPTION
**Pull request by nschan**
As of 24.03.0-edge nextflow's charliecloud driver has gained support for registry. This PR adds quay.io as the default registry for charliecloud.

### CODE REVIEW

**Review by mahesh-panchal — COMMENTED** [review]
Please update the comment above it and add a new line after the section

**Review by mahesh-panchal — APPROVED** [review]

**Review by maxulysse — COMMENTED** [review]
I like it, only issue I can see, is that we need the default Nextflow to be updated as well.
Should we wait for the next release, or do we want to have some edge releases in the TEMPLATE?

**Review by maxulysse — CHANGES_REQUESTED** [review]
I like it, only issue I can see, is that we need the default Nextflow to be updated as well.
Should we wait for the next release, or do we want to have some edge releases in the TEMPLATE?

**Comment by nschan** [comment]
That is a fair point, however charliecloud in nf-core is currently broken irrespective of these changes. I think adding this now and providing a config for people who want to use the edge release will not hurt, even if the default will only be updated with the next proper release?

**Review by mashehu — APPROVED** [review]

**Review by lrauschning — APPROVED** [review]

**Comment by nschan** [comment]
Thanks for approving, `charliecloud.registry` is actually still broken in 24.03.0-edge. I figured out how it is done now, see here https://github.com/nextflow-io/nextflow/pull/5018

**Comment by lrauschning** [comment]
@maxulysse can you approve it as well? then it can be merged when the nextflow version gets bumped to 24.04.
Have been using this config with the edge release without issues (thanks @nschan).

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
