### PR TITLE
Avoid checking pytest_modules file

### PR DESCRIPTION
**Pull request by Emiller88**
For the moment due to using anchors for it, the anchors with a '/' break pyyaml

https://github.com/nf-core/modules/pull/933

## PR checklist

 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by Emiller88** [comment]
Get's me every :upside_down_face:

**Comment by grst** [comment]
You could try using a `BaseLoader` like here:
https://github.com/nf-core/modules/blob/a6ca2b006b9eb4f1a07098966867c3c5fea42c51/tests/test_versions_yml.py#L17

According to the [docs](https://github.com/nf-core/modules/blob/a6ca2b006b9eb4f1a07098966867c3c5fea42c51/tests/test_versions_yml.py#L17)

> BaseLoader(stream) does not resolve or support any tags and construct only basic Python objects: lists, dictionaries and Unicode strings.

**Comment by Emiller88** [comment]
Okay, I think I just want to merge this for the moment, so we can get the subworkflows working with the linting. I'll come back to this, but I've gone down a rabbit hole with a circular dependency in the modules code that I want to fix.

**Comment by Emiller88** [comment]
Actually going to just see if I can point the ci to install this branch.

**Comment by rpetit3** [comment]
Locally I've replaced the `/` in the anchors (`&`) and references (`*`) with and underscore (`_`) and it makes things work nicely again. Would this be a viable solution on the `pytest_modules.yml`? it doesn't change the original test name.

**Comment by grst** [comment]
@Emiller88 , Is this still used anywhere? 

Can this be closed / merged /... ?

**Comment by Emiller88** [comment]
Yep, I believe this was fixed by  #1322

**Pull request closed without merging**
