### PR TITLE
Update MultiQC in pipeline template

### PR DESCRIPTION
**Pull request by jfy133**
Updates MultiQC to latest module version, correctly passes config file, and leaves note to add logo for display

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by jfy133** [comment]
Tried adding path to the default pipeline logo that is generated on  pipeline creation, but I couldn't see a good cookie cutter `{{ name }}` that doesn't have the slash

**Comment by jfy133** [comment]
After talking with @ewels it makes sense to actually just `mix` in the logo file as it's only used if specified within the multiqc_config itself (there is not a particular flag for MultiQC), I'll go back and update the moduel to remove it.

**Comment by jfy133** [comment]
Ok we do, because an intermediate update to the MultiQC module means all files given via `multiqc_files` are staged in 'random' directories. This then means you can't set the 'path' to the logo file in the  multiQC Config, as it would change between runs.

**Comment by jfy133** [comment]
Given I flipped back and forth another look would be good @maxulysse (sorry)

**Comment by apeltzer** [comment]
Maybe use MQC 1.13 stable which was released yesterday too ;-)

**Comment by jfy133** [comment]
FFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by ewels** [comment]
Bioconda PR was merged around 9am this morning, hopefully will be available before too much of a long wait.. 🤞🏻

**Pull request merged**
