### PR TITLE
Update test_yml_builder.py

### PR DESCRIPTION
**Pull request by SPPearce**
Moved the elem.replace line to before the test_file variable is created, so it now does something again, to make the test.yml file work correctly. I think this will resolve the issue of the tmp directory staying in the test.yml file #1371. 

## PR checklist

 - [X] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Thanks for this! Have you tested it though, does changing the path not break the md5 calculation and filesize check?

**Comment by ewels** [comment]
Just tested locally and as I feared, this breaks for `ucsc/liftover` (which has some empty files):

```
╭────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────╮
│ /opt/miniconda3/envs/py3.8/bin/nf-core:33 in <module>                                                                                  │
│                                                                                                                                        │
│   32 │   sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])                                                             │
│ ❱ 33 │   sys.exit(load_entry_point('nf-core', 'console_scripts', 'nf-core')())                                                         │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/__main__.py:62 in run_nf_core                                                                 │
│                                                                                                                                        │
│    61 │   # Lanch the click cli                                                                                                        │
│ ❱  62 │   nf_core_cli()                                                                                                                │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:829 in __call__                                                   │
│                                                                                                                                        │
│    828 │   │   """Alias for :meth:`main`."""                                                                                           │
│ ❱  829 │   │   return self.main(*args, **kwargs)                                                                                       │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:782 in main                                                       │
│                                                                                                                                        │
│    781 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                                                        │
│ ❱  782 │   │   │   │   │   rv = self.invoke(ctx)                                                                                       │
│    783 │   │   │   │   │   if not standalone_mode:                                                                                     │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:1259 in invoke                                                    │
│                                                                                                                                        │
│   1258 │   │   │   │   with sub_ctx:                                                                                                   │
│ ❱ 1259 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))                                                     │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:1259 in invoke                                                    │
│                                                                                                                                        │
│   1258 │   │   │   │   with sub_ctx:                                                                                                   │
│ ❱ 1259 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))                                                     │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:1066 in invoke                                                    │
│                                                                                                                                        │
│   1065 │   │   if self.callback is not None:                                                                                           │
│ ❱ 1066 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                                                      │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py:610 in invoke                                                     │
│                                                                                                                                        │
│    609 │   │   │   with ctx:                                                                                                           │
│ ❱  610 │   │   │   │   return callback(*args, **kwargs)                                                                                │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/site-packages/click/decorators.py:21 in new_func                                              │
│                                                                                                                                        │
│    20 │   def new_func(*args, **kwargs):                                                                                               │
│ ❱  21 │   │   return f(get_current_context(), *args, **kwargs)                                                                         │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/__main__.py:545 in create_test_yml                                                            │
│                                                                                                                                        │
│   544 │   │   meta_builder = nf_core.modules.ModulesTestYmlBuilder(tool, run_tests, output,                                            │
│       force, no_prompts)                                                                                                               │
│ ❱ 545 │   │   meta_builder.run()                                                                                                       │
│   546 │   except UserWarning as e:                                                                                                     │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:60 in run                                                         │
│                                                                                                                                        │
│    59 │   │   self.scrape_workflow_entry_points()                                                                                      │
│ ❱  60 │   │   self.build_all_tests()                                                                                                   │
│    61 │   │   self.print_test_yml()                                                                                                    │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:137 in build_all_tests                                            │
│                                                                                                                                        │
│   136 │   │   for entry_point in self.entry_points:                                                                                    │
│ ❱ 137 │   │   │   ep_test = self.build_single_test(entry_point)                                                                        │
│   138 │   │   │   if ep_test:                                                                                                          │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:191 in build_single_test                                          │
│                                                                                                                                        │
│   190 │   │                                                                                                                            │
│ ❱ 191 │   │   ep_test["files"] = self.get_md5_sums(entry_point, ep_test["command"])                                                    │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:270 in get_md5_sums                                               │
│                                                                                                                                        │
│   269 │   │                                                                                                                            │
│ ❱ 270 │   │   test_files = self.create_test_file_dict(results_dir=results_dir)                                                         │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:235 in create_test_file_dict                                      │
│                                                                                                                                        │
│   234 │   │   │   │   # Check that this isn't an empty file                                                                            │
│ ❱ 235 │   │   │   │   if self.check_if_empty_file(elem):                                                                               │
│   236 │   │   │   │   │   if not is_repeat:                                                                                            │
│                                                                                                                                        │
│ /Users/phil/GitHub/nf-core/tools/nf_core/modules/test_yml_builder.py:197 in check_if_empty_file                                        │
│                                                                                                                                        │
│   196 │   │   """Check if the file is empty, or compressed empty"""                                                                    │
│ ❱ 197 │   │   if os.path.getsize(fname) == 0:                                                                                          │
│   198 │   │   │   return True                                                                                                          │
│                                                                                                                                        │
│ /opt/miniconda3/envs/py3.8/lib/python3.8/genericpath.py:50 in getsize                                                                  │
│                                                                                                                                        │
│    49 │   """Return the size of a file, reported by os.stat()."""                                                                      │
│ ❱  50 │   return os.stat(filename).st_size                                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'output/ucsc/test.lifted.bed'
```

I'll see if I can push a fix..

**Comment by SPPearce** [comment]
> Thanks for this! Have you tested it though, does changing the path not break the md5 calculation and filesize check?

I haven't tested it at all, I'm not sure how to to be honest. I can vaguely read python but not write it. All I did was to try and move the replace line back above the append line, how it was before you made changes. My software-dev skills are still fairly minimal.

**Comment by ewels** [comment]
No worries! If you're curious, this is what I did to test it:

_In one terminal window, set to my local copy of my fork of this repo_
```bash
gh pr checkout 1372   # Check out a local copy of this pull request code, using the GitHub CLI tool
pip install -e .     # Reinstall the package, using -e ditable mode so that I don't need to keep reinstalling it when I edit stuff
```

_In another terminal window, where I have a copy of the modules repo checked out_
_(pasted in my test after I fixed the error)_
```console
❯ nf-core modules create-test-yml

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.2



INFO     Press enter to use default values (shown in brackets) or type your own responses                           test_yml_builder.py:55
? Tool name: ucsc/liftover
Test YAML output path (- for stdout) (tests/modules/ucsc/liftover/test.yml):
File exists! 'tests/modules/ucsc/liftover/test.yml' Overwrite? [y/n]: y
INFO     Looking for test workflow entry points: 'tests/modules/ucsc/liftover/main.nf'                             test_yml_builder.py:123
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_ucsc_liftover'                                                   test_yml_builder.py:157
Test name (ucsc liftover test_ucsc_liftover):
Test command (nextflow run tests/modules/ucsc/liftover -entry test_ucsc_liftover -c tests/config/nextflow.config):
Test tags (comma separated) (ucsc/liftover,ucsc):
Test output folder with results (leave blank to run test):
? Choose software profile  Docker
INFO     Running 'ucsc/liftover' test with command:                                                                test_yml_builder.py:320
         nextflow run tests/modules/ucsc/liftover -entry test_ucsc_liftover -c tests/config/nextflow.config
         --outdir /var/folders/w3/29y45jkn22vdl5dvctcgswvr33xvdd/T/tmpu7hisisc -work-dir
         /var/folders/w3/29y45jkn22vdl5dvctcgswvr33xvdd/T/tmprxb9ebf3
INFO     Repeating test ...                                                                                        test_yml_builder.py:323
INFO     Test workflow finished!                                                                                   test_yml_builder.py:336
INFO     Writing to 'tests/modules/ucsc/liftover/test.yml'                                                         test_yml_builder.py:353
CRITICAL Ran, but found errors:                                                                                            __main__.py:547
          - Empty file, skipping md5sum: 'test.unlifted.bed'
```

**Review by ewels — APPROVED** [review]
Happy with the fix now - I edited it slightly so that we still edit the path _after_ we use it to calculate md5s and check file sizes, however the path is now added to the `test_files` dict after the edit instead of before (as we had prior to this PR).

Thanks for spotting and proposing the fix @SPPearce!

**Comment by ewels** [comment]
ok and just pushed a minor refactor, I realised that the `git diff` was quite bit because the order of keys in the dictionary had changed (dicts are ordered in python 3) and this was reflected in the yaml. To avoid massive diffs on all PRs to modules for no reason, and because it makes more sense to read if the path is first, I refactored to keep the order of keys the same.

**Comment by SPPearce** [comment]
Ok, thanks for showing me how to checkout a specific PR and how to then reinstall the tools with pip. Complete newbie to python, should probably learn some of it at some point but that is somewhere near the bottom of an endless to-do list!

**Pull request merged**
