### PR TITLE
Update Sync Blacklist properly

### PR DESCRIPTION
**Pull request by apeltzer**
Drop:

- bcellmagic
- nascent
- atacseq 

from blacklist as these have template branches and are ready to receive updates in the future 👍 

Add:
    "sarek",
    "neutronstar",
    "proteomicslfq",
    "clinvap",
    "lncpipe",
    "ddamsproteomics",
    "scrnaseq",
    "guideseq"

As these are not ready yet.

### CODE REVIEW

**Comment by drpatelh** [comment]
@apeltzer  I havent merged the code that was used to create the `TEMPLATE` branch into `master` yet. I created it after the release.  Will that matter?

**Comment by drpatelh** [comment]
Hmm...maybe I should create a minor release before the next version of `tools`.

**Comment by Zethson** [comment]
@apeltzer Maybe one should update the [Documentation](https://nf-co.re/developers/sync) that the nf-core create command currently does NOT setup sync automatically. 
I was confused more than once about this until I found [this issue](https://github.com/nf-core/tools/issues/125) finally clearing things up.

It's not implemented yet.

**Comment by ewels** [comment]
Yeah, or perhaps we should just implement https://github.com/nf-core/tools/issues/125 - should be a fairly easy change I think..?

**Comment by apeltzer** [comment]
I'll do it in a separate branch!

**Comment by apeltzer** [comment]
Done: https://github.com/nf-core/tools/pull/330

**Pull request merged**
