### PR TITLE
Replace Slack link in enforcement section to core@ email alias

### PR DESCRIPTION
**Pull request by heuermh**
See #598

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by heuermh** [comment]
> It looks like this pull-request has been made against the heuermh/nf-core-tools master branch. The master branch on nf-core repositories should always contain code from the latest release. Because of this, PRs to master are only allowed if they come from the heuermh/nf-core-tools dev branch.

This message above is somewhat confusing, I believe it should read nf-core/tools master and dev branches instead of heuermh/nf-core-tools master and dev branches.  I am not sure why the branch protection check is failing, after changing the target to `nf-core:dev`.

**Comment by ewels** [comment]
Yeah, not confusing - plain wrong! When did that creep in? 🤔 

The test unfortunately does not re-run after you change the target branch, at least until you push a new commit. I haven't found a way around this yet.

**Review by ewels — APPROVED** [review]

**Comment by heuermh** [comment]
Thank you, @ewels!

**Comment by ewels** [comment]
Merged, thanks 👍🏻 

If you fancy it, we also need to update in a few other places 😓 

* https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/CODE_OF_CONDUCT.md
* https://github.com/nf-core/nf-co.re/blob/master/CODE_OF_CONDUCT.md

These are the ones that I can think of (aside from those in pipelines that should be updated by the sync / linting).

**Comment by ewels** [comment]
Here's the bit that prints that message:

https://github.com/nf-core/tools/blob/8c68650409a3f95376dd55c291dae5f9fc346347/.github/workflows/branch.yml#L26

> When thinking about branches, remember that the _base branch_ is **where** changes should be applied, the _head branch_ contains **what** you would like to be applied.

So I think it should be `base` instead of `head`..

```diff
+ ${{github.event.pull_request.base.repo.full_name}}
- ${{github.event.pull_request.head.repo.full_name}}
```

I'll prep a PR now..

**Pull request merged**
