### PR TITLE
Fix name of ModuleJson method call

### PR DESCRIPTION
**Pull request by fabianegli**
This PR adapts a method call to the changes in the method name and signature.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated

### CODE REVIEW

**Review by mashehu — APPROVED** [review]
Good catch! 🎣

**Comment by fabianegli** [comment]
@mashehu pylint is my friend 😉

**Comment by fabianegli** [comment]
`pylint --disable all --enable E nf_core` catches these kind of bugs.

**Comment by fabianegli** [comment]
@mirpedrol It would be nice if you could add some tests independently of this PR to call all methods at least once in a test.

**Comment by mirpedrol** [comment]
> @mirpedrol It would be nice if you could add some tests independently of this PR to call all methods at least once in a test.

Sounds good! I have a long list of tests to add 😂

**Comment by fabianegli** [comment]
@mashehu If you feel really adventurous, you can use `pylint --disable all --enable W nf_core`. And if you feel like you simply have too much time try `pylint nf_core` 🤓

**Comment by fabianegli** [comment]
> I have a long list of tests to add 😂

I know the feeling. If you write the tests before you make changes to the code, they help you know when you are done and immediately boos your confidence in the code you just wrote. It's not always what I do, but it's definitely worth a try.

**Pull request merged**
