### PR TITLE
respect indentation on version bump

### LINKED ISSUE #2206: nf-core tools `bump-version` command does not preserve formatting
### Description of feature

When running `nf-core bump-version 1.1.0` I get the following diff:

```
% git diff
diff --git a/nextflow.config b/nextflow.config
index ee0fca4..c249288 100644
--- a/nextflow.config
+++ b/nextflow.config
@@ -366,7 +366,7 @@ manifest {
     description     = """Quantitative Mass Spectrometry nf-core workflow"""
     mainScript      = 'main.nf'
     nextflowVersion = '!>=22.10.1'
-    version         = '1.1dev'
+    version = '1.1.0'
     doi             = ''
 }
```

but would expect

```
% git diff
diff --git a/nextflow.config b/nextflow.config
index ee0fca4..c249288 100644
--- a/nextflow.config
+++ b/nextflow.config
@@ -366,7 +366,7 @@ manifest {
     description     = """Quantitative Mass Spectrometry nf-core workflow"""
     mainScript      = 'main.nf'
     nextflowVersion = '!>=22.10.1'
-    version         = '1.1dev'
+    version         = '1.1.0'
     doi             = ''
 }
```
instead.

### PR DESCRIPTION
**Pull request by mashehu**
fixes #2206

### CODE REVIEW

**Comment by fabianegli** [comment]
I think it would be great to have a small specific test for that 😉

And I would have gone with capturing the spaces for preservation. Something like this:

```python
                rf"version(\s*)=\s*[\'\"]?{re.escape(current_version)}[\'\"]?",
                rf"version\1= '{new_version}'",
```

**Review by mirpedrol — APPROVED** [review]
Love it ❤️

**Comment by mashehu** [comment]
happy now with it, @fabianegli?

**Comment by fabianegli** [comment]
Very 😄

**Pull request merged**
