### PR TITLE
workaround for shutil.copytree's lack of dirs_exist_ok in Python3.7 + added tests for module patch

### PR DESCRIPTION
**Pull request by fabianegli**
Fix issue introduced by https://github.com/nf-core/tools/pull/1755

Not sure what to write in the changelog.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by ewels — APPROVED** [review]
image

**Comment by fabianegli** [comment]
We need a review fro a non-co-author.

What was the workflow to get the commits into this PR with the nf-core_bot? They seem to be displayed a bit funny and also the attribution to the author seems to be lost in translation which I find strange.

**Comment by fabianegli** [comment]
@ewels Thanks!

**Comment by ewels** [comment]
> What was the workflow to get the commits into this PR with the nf-core_bot? They seem to be displayed a bit funny and also the attribution to the author seems to be lost in translation which I find strange.

Sorry only just saw this after I clicked merge. I don't follow sorry, what was the question?

**Comment by fabianegli** [comment]
The messages must have crossed.

Normally there is some attribution in the commit message line in a PR, but here it isn't. It's not a big issue, I just wonder how this was done.

Screenshot 2022-08-23 at 12 33 15

**Comment by ewels** [comment]
Right, I see now - _nf-core_bot added 3 commits [1 hour ago]_ uhmmm.. I have no idea what has happened here 👀 

@nf-core-bot can do some stuff to do with fixing linting, but this is `nf-core_bot` which looks different. I have no idea where these commits have come from.

**Comment by mashehu** [comment]
these are commits I pushed...

**Comment by fabianegli** [comment]
@mashehu Could you push directly to that branch? Or did you use the `gh` tool?

**Comment by mashehu** [comment]
I pushed directly to the branch (but now after lunch I got a permission errors 🙂)

**Comment by fabianegli** [comment]
Thank you for the info - although I am not sure what to make of it. I'll probably avoid pushing to other branches directly 🤷‍♂️

**Comment by ewels** [comment]
ahh ok so @mashehu confuses us all by changing his local git username 😅 

We have been in the habit of pushing directly to other people's PRs is fairly regularly within nf-core but yeah, it can be odd if you're not used to it. It's very easy to do with `gh` but you can do it with native `git` too, just a case of setting up the remotes. The permissions is handled by GitHub - if you're not keen then you can disable it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by fabianegli** [comment]
@ewels Thank you or explanation and the link.

**Comment by mashehu** [comment]
[workaround for copytree+test](https://trello.com/c/fM04pXGq/3-workaround-for-copytreetest)

**Pull request merged**
