### PR TITLE
Schema build bug

### PR DESCRIPTION
**Pull request by ewels**
Fix issues with the `schema  build` code that was doing weird stuff when making a new schema - bug found by @mashehu 

Also revert the template JSON schema back to 4-space padding instead of 2, to limit the diffs when people edit their schema from the template.

### CODE REVIEW

**Comment by ewels** [comment]
Diff without whitespace: https://github.com/nf-core/tools/pull/699/files?diff=unified&w=1

**Comment by mashehu** [comment]
I think we should favor the web builder, so the Launch web builder should be [Y/n].
I don't have enough familiarity with cli layouting (yet), but could we indent the launch dialog and have the space between "🚀" and "Launch" not ignored:
Screenshot 2020-07-29 at 11 23 05

**Comment by ewels** [comment]
> I think we should favor the web builder, so the dialog should be a [Y/n].

It did have this previously, but when I switched to using `rich` for this I removed the defaults for all confirmation prompts. At the time I was thinking that it was better to have people actively think about it rather than just hitting enter, but maybe you're right and we should set it to true by default in this case.

> have the space between "🚀" and "Launch" not ignored:

Odd, that has a space for me:

image

I'll double-space it and add some indentation.

**Comment by ewels** [comment]
image

**Comment by mashehu** [comment]
Duplication bug seems to be fixed now. One more bug: the command line keeps waiting for form completion, even after I clicked finished in the browser.

**Comment by ewels** [comment]
Good spot, fixed in https://github.com/nf-core/nf-co.re/pull/467

**Comment by ewels** [comment]
Now that the website bug has been fixed and merged / deployed, this should work as advertised 👍🏻

**Comment by mashehu** [comment]
Yes, works as advertised!

**Pull request merged**
