### PR TITLE
transparently use the print function from rich

### PR DESCRIPTION
**Pull request by fabianegli**
I find replacing builtin functions intransparent and hence propose to make the use of rich.print obvious.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Generally I agree, however in this case it's the recommended usage pattern and the most commonly implemented style: https://rich.readthedocs.io/en/stable/introduction.html#quick-start

I'm happy enough to change it. Though if we're going to go to the effort of this change it might be even nicer to create a shared `Console` object which takes arguments about forced colour (and more) and pass that around. We already have one for stderr I believe.

**Comment by fabianegli** [comment]
I agree, the shared object would be better than the current PR. There are already a range of files that follow the Console approach for standard error.

Nitpick: The docs state that the from rich import print is the *quickest* way to get started, not the most readable or maintainable.

**Review by ewels — APPROVED** [review]
LGTM 👍🏻 Thanks!

**Comment by ewels** [comment]
@mashehu - this change might help with the rich-codex screenshots. Hopefully some of the output will be more colourful now 🌈

**Pull request merged**
