### PR TITLE
Put the TODO comment in a YAML array.

### PR DESCRIPTION
**Pull request by charles-plessy**
The `contains:` map needs an array of strings.  By placing the TODO comment between brackets I hope that the user will be more likely to produce a valid file. 

Closes: #1082

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by KevinMenden** [comment]
Thanks @charles-plessy ! Looks good to me ... it's only failing because of those annoying module lint tests. Really should go about improving them somehow 🤔

**Comment by KevinMenden** [comment]
@charles-plessy if you could pull the most recent changes from dev into your branch, then those tests should be fixed.

**Comment by charles-plessy** [comment]
@KevinMenden sorry that I used the `master` branch instead of `dev`. I see that you already made a merge; do I have to do something else?

**Comment by KevinMenden** [comment]
You would need to merge the most recent changes from `nf-core/tools:dev` into your current `path-1` branch, this will fix the tests.

**Review by KevinMenden — APPROVED** [review]

**Pull request merged**
