### PR TITLE
Fix comment section headers so they don't give phantom merge conflict warnings

### PR DESCRIPTION
**Pull request by jfy133**
Because `====` is used in git conflict merges

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Review by mashehu — CHANGES_REQUESTED** [review]
can't change it in the nf-core modules... needs to go through the modules repo

**Comment by jfy133** [comment]
Gah!

**Comment by jfy133** [comment]
https://github.com/nf-core/modules/pull/6755

**Comment by mirpedrol** [comment]
But the local subworkflow has to be changed here 😄

**Comment by jfy133** [comment]
Gah!

**Comment by mirpedrol** [comment]
I will reopen this PR to fix the local subworkflow and update the others which you fixed in modules

**Comment by jfy133** [comment]
I'll fix this now @mirpedrol !

**Review by mashehu — APPROVED** [review]

**Pull request merged**
