### PR TITLE
Create template logo

### LINKED ISSUE #233: Email template doesn't use ASCII art
The plain text email formatting needs updating to fit in with the look and feel of other command line output ✨

### LINKED ISSUE #316: Add logo to email template
A few pipelines have now followed suit with `nf-core/rnaseq` to include the pipeline logo in the completion email. It would be nice to add this to the template. 

Small changes would be required to the `email_template.*` files in the assets directory. The creation of the logo itself is a standalone process at the moment. Either it's kept that way and placed in `assets/` with the appropriate name or its somehow generated with `nf-core create`. Not sure how difficult the latter will be because custom fonts are required to be installed.

### PR DESCRIPTION
**Pull request by ewels**
Template and create - better logos

* Plaintext email template now has nf-core ASCII artwork. Fixes #233 
* `nf-core create` now fetches a logo from the nf-core website in two sizes, template is configured to use them for the readme and HTML email. Fixes #316 

Note that I haven't tested the email yet as using email on this machine is a hassle. Bonus points if any reviewers can make a pipeline, run it and check that the email displays properly... 😁

### CODE REVIEW

**Comment by drpatelh** [comment]
Amazing! Thanks. Do you think this needs to be fixed too? If you settle for height scaling instead then the download command will need to be updated here.
https://github.com/nf-core/nf-co.re/issues/172

**Comment by drpatelh** [comment]
I think all of the pipelines that provide the logo in the email at the moment used the old logo creation method with height = 200px (README logo) and height = 150px (email logo).

**Comment by ewels** [comment]
> Do you think this needs to be fixed too?

Yes, yes - give me a second.. 😆 https://github.com/nf-core/nf-co.re/pull/198

> I think all of the pipelines that provide the logo in the email at the moment used the old logo creation method with height = 200px (README logo) and height = 150px (email logo).

Sure, but the website resizes based on width, not height. I think that's probably safer.. Or is there a reason to base it on height instead?

**Comment by drpatelh** [comment]
No, not particularly. If you think it's better to use width then I'm poppin!

**Comment by ewels** [comment]
No idea why the LGTM tests are failing. It's the one that is meant to look at JavaScript, of which there is none. I should really disable that for this repo... I tried rerunning but it doesn't seem to be having any effect.

Other tests are passing ✅

**Comment by drpatelh** [comment]
We have a merge conflict?

**Comment by ewels** [comment]
Resolved ✅ 

Should now rerun the tests with the new commit too, so double-win..

**Comment by ewels** [comment]
Still no LGTM love.. 😭 

Travis is the only one that really matters here though..

**Pull request merged**
