### PR TITLE
QBIC Specific Config Template Updates

### PR DESCRIPTION
**Pull request by apeltzer**
This updates both binac and cfc system configs for general usage across pipelines. Once we use the syncing process, this should (and could!) be synced across all pipelines :-) 

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by sven1103** [comment]
Thanks @apeltzer ! Could you please also update the CHANGELOG, so that the `pip install --upgrade  pip` change for the environment is written down, and the updated configs.

**Comment by apeltzer** [comment]
There u go

**Comment by ewels** [comment]
Should we add some documentation for these configs in the template docs too?

**Comment by apeltzer** [comment]
Yes we definitely should to have it consistently present in all pipelines...!

**Comment by ewels** [comment]
Tests are failing, but I don't think that it's your fault.. I think it was mine: https://github.com/nf-core/tools/pull/184

**Pull request merged**
