### PR TITLE
Added alternative installation method via conda

### PR DESCRIPTION
**Pull request by jfy133**
Many thanks for contributing to nf-core/tools!

Some people (including myself) often find installation of programs from conda with `conda install` can be a bit buggy. Therefore @drpatelh suggested creating an environment for nf-core/tools and running from that instead. This PR describes how to do this.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by ewels** [comment]
While I appreciate the PR and am glad this fixed the issue for you @jfy133, I'm not sure that we really want this in the docs? I think that creating an environment file for a single package is not really best practice for how to use conda.

Instead, could we not just put more emphasis on following the bioconda config instructions, and mention that a new environment can be created in case of problems? If conda channels are configured then it's a one liner: `conda create --name nf-core python=3.7 nf-core`

Can even install nextflow in the same command:
`conda create --name nf-core python=3.7 nf-core nextflow`

**Comment by jfy133** [comment]
Also fine with me, indeed getting the channels to work was the problem (although it was some more wierd setup stuff I had to do due to a new laptop).

You might be right to suggest putting more emphasis on setting up bioconda properly. Just saying 'Using bioconda' to me says use that channel, i.e. a repository - particularly when the command includes `-c bioconda`. 

For new users they may not realise you have to do special things to actually use that channel. I can change this this evening if you would like.

**Comment by ewels** [comment]
Yes, we should remove the `-c bioconda` bit 👍

**Comment by ewels** [comment]
Ok, I had it open so I drafted something quickly here: https://github.com/nf-core/tools/pull/573

**Pull request merged**
