### PR TITLE
Provide unit-tests for 'download' subcommand

### PR DESCRIPTION
**Pull request by sven1103**
- Increase the test coverage for nf-core tool's sub-command `download`.
- Refactor class code, in order to make unit-test code easier to implement

### CODE REVIEW

**Comment by ewels** [comment]
Sorry @sven1103 - I merged the other PR and it broke the tests here 😨

**Comment by ewels** [comment]
Ah no wait, it was my last minute change that was broken - nothing to do with the tests. Sorry! Shouldn’t do late night merges.. :sweat_smile:

**Comment by ewels** [comment]
Ok, all fixed - let's pretend that the last 12 hours didn't happen 😅

**Comment by sven1103** [comment]
@ewels : och, thanks, likewise!! I am still a novice in unit-testing and mocking makes me crazy sometimes :sweat_smile:

**Pull request merged**
