### PR TITLE
refactor: remove the mulled command and all related code

### PR DESCRIPTION
**Pull request by Midnighter**
Based on [Slack discussion](https://nfcore.slack.com/archives/CE5LG7WMB/p1677857660211839?thread_ts=1676237965.409659&cid=CE5LG7WMB), we decided to completely remove the mulled command and its dependencies.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [x] Documentation in `docs` is updated

### CODE REVIEW

**Review by mirpedrol — APPROVED** [review]
Thanks!

**Comment by mirpedrol** [comment]
Should we also add a link to your app in the documentation?

**Comment by Midnighter** [comment]
If you like, we can surely do that.

**Comment by mirpedrol** [comment]
I have added the link to the documentation https://github.com/nf-core/nf-co.re/pull/1743 and will merge this if that's ok @Midnighter

**Comment by Midnighter** [comment]
Please go ahead, yes ☺️

**Pull request merged**
