### PR TITLE
Add code lint CI PR comments to pipeline template

### PR DESCRIPTION
**Pull request by ewels**
Added linting CI test PR comments for all code language linting in the pipeline template. Tweaked the markdown comment slightly for tools too.

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by KevinMenden — APPROVED** [review]
👍

**Comment by KevinMenden** [comment]
No idea why it doesn't recognise the token. Maybe define it before the `with` statement as environment variable and then grab it again?

**Comment by ewels** [comment]
> No idea why it doesn't recognise the token. Maybe define it before the `with` statement as environment variable and then grab it again?

It's not a Jinja variable, it's a GitHub Actions variable. Just needed wrapping in `{% raw %}` so that Jinja ignores it.

**Comment by ewels** [comment]
After messing with `testpipeline` for a while to test this, it doesn't work.

Same permissions error we've hit previously where the CI is running on the base fork for a PR and doesn't have permissions to post a comment on the PR. We have a workaround for the `nf-core lint` results but I'm not sure that I can be bothered to try to do the same for markdownlint and yaml right now.

Will leave in as it works for branches and can try to do this another time maybe.

**Pull request merged**
