### PR TITLE
Dev -> Master for v2.7

### PR DESCRIPTION
**Pull request by mirpedrol**
## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mashehu — APPROVED** [review]
Let's go!

**Comment by awgymer** [comment]
Should we add/expand docs on how to structure your own private modules repo and some of the possible gotchas?

**Review by ewels — APPROVED** [review]

**Comment by mashehu** [comment]
> Should we add/expand docs on how to structure your own private modules repo and some of the possible gotchas?
> 
> 
> 
> I am thinking particularly regarding `org_path` in the `.nf-core.yml` and the risks of having two modules with the same name. 
> 
> 
> 
> If these are already done and I missed it ignore me. Otherwise I could work on some tomorrow?

Good idea, but I think these would be over at the nf-co.re repo and not needed here, right?

**Comment by awgymer** [comment]
Hmm maybe. I only reviewed the readme on the main page and there are some comments about private repos and needing a "structure" but nothing specific. I would probably at least link to wherever we will put them on nf-co.re

**Comment by mirpedrol** [comment]
We have some documentation on the [readme](https://github.com/nf-core/tools/tree/dev#custom-remote-modules). We could add a sentence about `org_path`. I opened a [PR](https://github.com/nf-core/tools/pull/2109), please make all the changes that you consider 🙂 Then we can release 🚀

**Pull request merged**
