### PR TITLE
bump nf-schema to v2.1.1 in the template

### PR DESCRIPTION
**Pull request by nvnieuwk**
## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Review by mirpedrol — APPROVED** [review]
Is the bug with `defaultIgnoreParams` solved in 2.1.1?

**Comment by nvnieuwk** [comment]
Yes it is! and some other small fixes that were detected

**Comment by mirpedrol** [comment]
Nice! Thanks for removing the params. Ok for me to merge. I re-run the tests, they should all pass now

**Comment by nvnieuwk** [comment]
One is still failing but it doesn't look like it's related to this PR (ontology linting) so I'll go ahead and merge :)

**Pull request merged**
