### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by MaxUlysse**
Many thanks to contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- Correct typo

## PR checklist
 - [X] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Travis is failing, is that normal?

**Comment by apeltzer** [comment]
No, its one of these weird TravisCI errors we've been seeing recently. No idea why.... your PR looks fine to me...

**Comment by phue** [comment]
It's failing because CHANGELOG.md was not updated. I.e. if the linecount of the file stays the same, the build fails.

**Comment by drpatelh** [comment]
Master is only updated on release so its probably easier to keep track of things that have been updated if you amend the `CHANGELOG` every time you change the `dev` code.

**Comment by ewels** [comment]
The changelog test is annoying as hell, but I have to say that our changelogs have become a lot more descriptive since it's been in place 😇

**Comment by drpatelh** [comment]
@MaxUlysse Can you sync this with the current `dev` branch and update `CHANGELOG` please? Be good to merge and close this 👍

**Comment by MaxUlysse** [comment]
I'm sorry, I did not notice your comment earlier, I'm on it.

**Pull request merged**
