### PR TITLE
Download: Get DSL2 singularity containers

### LINKED ISSUE #513: nf-core download: Handle multiple containers
At the moment, if used with `--singularity` then `nf-core download` expects there to only be a single container and pulls that. There are however some pipelines that need more than one (sarek, neutronstar and more) and there will be many more (all) in the future.

Need to instead parse all instances of `process.container` if possible and automatically pull all required singularity images.

Would be good to combine with https://github.com/nf-core/tools/issues/464 to also automatically configure the pipeline with paths so that it knows where these containers are out of the box.

### PR DESCRIPTION
**Pull request by ewels**
With DSL2, we have multiple containers and they are specified within module files. These are no longer found by `nextflow config` and therefore `nf-core download` doesn't see them (#818).

This PR adds several new bits of functionality to `nf-core download` for singularity containers:

### Finding DSL2 containers

The tool now scrapes any `.nf` files in `modules/` recursively, and parses them to look for a lines that look like this:

```nextflow
container = "xxx"
```

If multiple matches are found in a file, any that start with `http` are prioritised and the first match after that is used.

> NB: Scraping code only handles simple strings and will fail with anything more complicated (e.g. [Sarek](https://github.com/nf-core/sarek/blob/bce378e09de25bb26c388b917f93f84806d3ba27/conf/base.config#L71)). This kind of thing needs to be resolved by Nextflow and so requires `nextflow config` or similar to work. I can't see any way around this in the scope of this PR.

### Direct image downloads

The code  can now directly download images if we have a URL. If the container name starts with `http` then we download this directly in Python. If not, then we pass to a `singularity pull` command as before. Python downloads are made pretty with a nice progress bar etc.

### Caching downloads

Finally, the code now checks for the `NXF_SINGULARITY_CACHEDIR` environment variable and saves singularity images there first if set, before copying to the archive. This speeds things up massively if running a few times and will be increasingly important with shared images across multiple DSL2 pipelines. If the env var is not set then the files are saved directly to the archive, but a log message with a tip about it is shown.

## Still to do:

- [x] Update the downloaded pipeline code so that it knows where to find the bundled singularity images (#464)
- [x] Check that auto-generated image names from https downloads are the same as those made by Nextflow
- [x] Figure out how to have nested Progress bars with different columns in Rich.
    - Have a global progress bar showing how far through all containers we are, then a transient progress bar for each download.
- [x] More testing (check DSL1 pipelines still work)

**Note 1:** This PR does not fix #513, but I suspect that this will be less of a problem as all pipelines transition to DSL2 so I think that we can probably ignore that issue now.

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [x] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
Simultaneous downloads are awesome, but now `ctrl-c` doesn't cleanly exit. Any ideas?

**Comment by MaxUlysse** [comment]
Still thinking about complicated cases.
(Sarek obviously).
I can make the list of containers more clear, so that it's easy to read, but we probably don't need to download all containers all the time.
(I'm mainly thinking here for the annotation, I don't need to download the huge human containers if I'm only working with mouse for example)
Any way to control that?

**Comment by ewels** [comment]
I don't think that this will change anything for Sarek. `nf-core download` currently ignores those containers, right? I think that will still be the case after this PR unless you move them into DSL2 module files that have exactly the right formatting.

**Comment by MaxUlysse** [comment]
OK, we'll figure it out then.

**Comment by drpatelh** [comment]
If you want a good test for this then you can try my fork of viralrecon https://github.com/drpatelh/nf-core-viralrecon/tree/dsl2. It's not finished but currently contains a mixture of modules that have explicit download paths to Singularity images as well as one that doesn't https://github.com/drpatelh/nf-core-viralrecon/blob/c4747d1691977e02ae90766ad9257d34ae1546fe/modules/local/spades.nf#L14

**Comment by ewels** [comment]
> If you want a good test for this then you can try my fork of [viralrecon](https://github.com/drpatelh/nf-core-viralrecon/tree/dsl2). It's not finished but currently contains a mixture of modules that have explicit download paths to Singularity images as well as [one](https://github.com/drpatelh/nf-core-viralrecon/blob/c4747d1691977e02ae90766ad9257d34ae1546fe/modules/local/spades.nf#L14) that doesn't.

Sounds great! Also a good test that it works with random forks and branches. To be honest, I really didn't expect it to, but what d'you know?!

```console
❯ nf-core download drpatelh/nf-core-viralrecon -r dsl2

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 1.13.dev0



WARNING  Pipeline name doesn't match any nf-core workflows
INFO     Pipeline name looks like a GitHub address - attempting to download anyway
INFO     Saving drpatelh/nf-core-viralrecon
          Pipeline release: 'dsl2'
          Pull singularity containers: 'No'
          Output file: 'drpatelh-nf-core-viralrecon-dsl2.tar.gz'
INFO     Downloading workflow files from GitHub
INFO     Downloading centralised configs from GitHub
INFO     Compressing download..
INFO     Command to extract files: tar -xzf drpatelh-nf-core-viralrecon-dsl2.tar.gz
INFO     MD5 checksum for drpatelh-nf-core-viralrecon-dsl2.tar.gz: d10c52e0fdb5c4c168ff29912689a82c
```

💥 

Will try with Singularity now..

**Comment by ewels** [comment]
Ah, that's good to see - it's copying a bunch of images from the cache that have already been downloaded in my tests of the rnaseq pipeline. Nice! ⏩ 

New direct downloads now running, I expect that they will finish and then hopefully it will try to pull the one singularity image and fail because I don't have singularity installed on my mac.

**Comment by ewels** [comment]
@drpatelh - looks good I think!

```console
❯ nf-core download drpatelh/nf-core-viralrecon -r dsl2 --force --compress none --singularity

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 1.13.dev0



WARNING  Pipeline name doesn't match any nf-core workflows                                                                                                             download.py:225
INFO     Pipeline name looks like a GitHub address - attempting to download anyway                                                                                     download.py:226
WARNING  Deleting existing output directory: 'drpatelh-nf-core-viralrecon-dsl2'                                                                                        download.py:130
INFO     Saving drpatelh/nf-core-viralrecon                                                                                                                            download.py:142
          Pipeline release: 'dsl2'
          Pull singularity containers: 'Yes'
          Using '$NXF_SINGULARITY_CACHEDIR': /Users/ewels/GitHub/nf-core/tools/testing/nf-core-rnaseq-3.0-nocache/singularity-images
          Output directory: 'drpatelh-nf-core-viralrecon-dsl2'
INFO     Downloading workflow files from GitHub                                                                                                                        download.py:145
INFO     Downloading centralised configs from GitHub                                                                                                                   download.py:149
INFO     Fetching container names for workflow                                                                                                                         download.py:315
INFO     Found 29 containers                                                                                                                                           download.py:350
Downloading singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━  86% • 25/29 completed
Copying from cache to target directory ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 842.0/842.0 MB • 1.3 MB/s
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━  90% • 26/29 completed



                                                                                                                                                                                      
ERROR    Singularity is not installed!                                                                                                                                 download.py:604
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 29/29 completed




```

Output looks good:

```console
 ❯ tree -L 2 drpatelh-nf-core-viralrecon-dsl2
drpatelh-nf-core-viralrecon-dsl2
├── configs
│   ├── LICENSE
│   ├── README.md
│   ├── assets
│   ├── bin
│   ├── conf
│   ├── configtest.nf
│   ├── docs
│   ├── nextflow.config
│   ├── nfcore_custom.config
│   └── pipeline
├── singularity-images
│   ├── containers.biocontainers.pro-s3-SingImgsRepo-biocontainers-v1.2.0_cv1-biocontainers_v1.2.0_cv1.img.img
│   ├── depot.galaxyproject.org-singularity-bandage-0.8.1--hc9558a2_2.img
│   ├── depot.galaxyproject.org-singularity-bcftools-1.11--h7c999a4_0.img
│   ├── depot.galaxyproject.org-singularity-bedtools-2.30.0--hc088bd4_0.img
│   ├── depot.galaxyproject.org-singularity-blast-2.10.1--pl526he19e7b1_3.img
│   ├── depot.galaxyproject.org-singularity-bowtie2-2.4.2--py38h1c8e9b9_1.img
│   ├── depot.galaxyproject.org-singularity-cutadapt-3.2--py38h0213d0e_0.img
│   ├── depot.galaxyproject.org-singularity-fastp-0.20.1--h8b12597_0.img
│   ├── depot.galaxyproject.org-singularity-fastqc-0.11.9--0.img
│   ├── depot.galaxyproject.org-singularity-ivar-1.3--h089eab3_0.img
│   ├── depot.galaxyproject.org-singularity-kraken2-2.1.1--pl526hc9558a2_0.img
│   ├── depot.galaxyproject.org-singularity-minia-3.2.4--he513fc3_0.img
│   ├── depot.galaxyproject.org-singularity-mosdepth-0.3.1--ha7ba039_0.img
│   ├── depot.galaxyproject.org-singularity-mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a-577a697be67b5ae9b16f637fd723b8263a3898b3-0.img
│   ├── depot.galaxyproject.org-singularity-mulled-v2-ad9dd5f398966bf899ae05f8e7c54d0fb10cdfa7-05678da05b8e5a7a5130e90a9f9a6c585b965afa-0.img
│   ├── depot.galaxyproject.org-singularity-multiqc-1.9--pyh9f0ad1d_0.img
│   ├── depot.galaxyproject.org-singularity-picard-2.23.9--0.img
│   ├── depot.galaxyproject.org-singularity-plasmidid-1.6.3--1.img
│   ├── depot.galaxyproject.org-singularity-python-3.8.3.img
│   ├── depot.galaxyproject.org-singularity-quast-5.0.2--py37pl526hb5aa323_2.img
│   ├── depot.galaxyproject.org-singularity-requests-2.24.0.img
│   ├── depot.galaxyproject.org-singularity-samtools-1.10--h9402c20_2.img
│   ├── depot.galaxyproject.org-singularity-snpeff-5.0--0.img
│   ├── depot.galaxyproject.org-singularity-snpsift-4.3.1t--2.img
│   ├── depot.galaxyproject.org-singularity-unicycler-0.4.8--py38h8162308_3.img
│   └── depot.galaxyproject.org-singularity-varscan-2.3.7--3.img
└── workflow
    ├── CHANGELOG.md
    ├── CITATIONS.md
    ├── CODE_OF_CONDUCT.md
    ├── LICENSE
    ├── README.md
    ├── assets
    ├── bin
    ├── conf
    ├── docs
    ├── lib
    ├── main.nf
    ├── modules
    ├── nextflow.config
    ├── nextflow_schema.json
    ├── subworkflows
    └── workflows

16 directories, 39 files
```

**Comment by drpatelh** [comment]
Ok. Let me give it a test with Singularity to see if it pulls that lonesome SPAdes image properly too 👍🏽

**Comment by ewels** [comment]
> Ok. Let me give it a test with Singularity to see if it pulls that lonesome SPAdes image properly too 👍🏽

Sounds good - always nice to put it in someone else's hands! 😅 I'm 90% sure it should work because I haven't touched the code that does the singularity pull. So once it said that it was trying to I was fairly happy. Would be good to actually confirm that it does though.

**Comment by drpatelh** [comment]
Would it be worth creating the Singularity cache directory if it doesn't exist already?

```
FileNotFoundError: Output directory not found: 'test/containers'
```

**Comment by drpatelh** [comment]
Got this error. Assume that can only be when trying to pull and convert the SPAdes Docker image? Container name isn't reported in the error anywhere - maybe that's a good idea too?

```
TypeError: singularity_pull_image() takes 4 positional arguments but 5 were given
``

**Comment by ewels** [comment]
oops sorry! I hit the same error just earlier and fixed it, but apparently failed to commit / push 🤦🏻 

Now pushed - should work now.

**Comment by ewels** [comment]
> Would it be worth creating the Singularity cache directory if it doesn't exist already?
> 
> ```
> FileNotFoundError: Output directory not found: 'test/containers'
> ```

Done 👍🏻

**Comment by drpatelh** [comment]
I can confirm that it works to pull Singularity images directly and converting from Docker 🎉 

```bash
export NXF_SINGULARITY_CACHEDIR=./test/containers
nf-core download drpatelh/nf-core-viralrecon -r dsl2  --force --compress none --singularity --parallel_downloads 6
```

Although, I get some weird log output during the Docker -> Singularity conversion. That could be our local terminal set-up though...

image

Also tested by re-running the same command and it picks up the cached images as expected! 

Nice work @ewels 😎

**Comment by ewels** [comment]
Ah would be nice to try to scoop up those singularity log outputs so that they don't mess up the display really 🤔 

Thanks for testing! 🚀  Will try to tidy that up when I get a chance, then write some docs and make the PR ready for merge.

**Comment by MaxUlysse** [comment]
@ewels Trying it out too, but where do you need to have the singularity files defined?

**Comment by drpatelh** [comment]
Which repo are you trying it out on? I think it should be any file in `modules/`. The file themselves can either container something like [this](https://github.com/drpatelh/nf-core-viralrecon/blob/c82eb410b0d9dabbce87444f044e30becbc35efe/modules/local/samtools_view.nf#L15-L17) or [this](https://github.com/drpatelh/nf-core-viralrecon/blob/c82eb410b0d9dabbce87444f044e30becbc35efe/modules/local/spades.nf#L14).

**Comment by MaxUlysse** [comment]
ok, fixed.
Thanks for the tips @drpatelh

**Comment by MaxUlysse** [comment]
Works wonderfully nice.
I know have a couple of questions:
 - If I were to use a `$NXF_SINGULARITY_CACHEDIR` that is shared with other pipelines, will it try to re-download shared containers?
- I do need to respect the way of specifying the containers that is specified in @drpatelh examples I suppose. But how can it work if I have several containers available for a single process?

Also, the `Downloading singularity images` progress bar always stayed to 0% until the end in my case (`zsh` user here).

**Comment by MaxUlysse** [comment]
cf https://github.com/nf-core/sarek/pull/338/commits/5ce928f681056f428af1f954e10dd9ce8be867f5
I had to change all that to make it work.

**Comment by ewels** [comment]
> If I were to use a `$NXF_SINGULARITY_CACHEDIR` that is shared with other pipelines, will it try to re-download shared containers?

Nope, if it finds the image it needs there then it will just copy it to the target directory (unless you specify `--singularity-cache`, in which case it will just leave it there). Same for re-downloading a pipeline more than once, or getting different versions etc.

> I do need to respect the way of specifying the containers that is specified in @drpatelh examples I suppose. But how can it work if I have several containers available for a single process?

I don't know, that's a problem for you to figure out I'm afraid 😆  It's definitely a problem with these huge containers that keep all of the reference files inside. But I can't see an easy way to get around it either for now. Do you have some example container URLs and associated use cases?

> Also, the `Downloading singularity images` progress bar always stayed to 0% until the end in my case (`zsh` user here).

That's a shame! Do the progress bars for each image download work ok?

**Comment by ewels** [comment]
> cf [nf-core/sarek@5ce928f](https://github.com/nf-core/sarek/commit/5ce928f681056f428af1f954e10dd9ce8be867f5)
> I had to change all that to make it work.

Yes sorry, this is the downside of using a method that does simple file scraping! I'm a bit worried that it will be too fragile and miss stuff. We'll just have to see though...

**Comment by ewels** [comment]
Ok, done a load more testing and bugfixing, written some docs, hopefully should be about ready to go now I think.

@drpatelh / @MaxUlysse would be great if you guys could give it another test! I rewrote how the logging works for the Singularity pull containers so now that's beautiful as well 🤩  (and you know that something is actually happening..)

Phil

**Comment by ewels** [comment]
Singularity image pull demo:

https://user-images.githubusercontent.com/465550/106531319-4b1b3380-64ee-11eb-9fbe-5734c06f7d77.mp4

**Comment by MaxUlysse** [comment]
Trying the latest version now.
The `Downloading singularity images` progress bar is working for me now.

**Comment by MaxUlysse** [comment]
Now, my only issue is to figure out how not to download every modules...

I don't really care if people download both the gatk and the gatk_spark modules, it won't take that much space.
(or even all the modules that people won't use because sarek has a lot of choice...)

But the extra containers for annotation are something else.
So currently my plan is to write the declaration for said containers in a way that is not recognized by tools, and get people to download separately.

Sounds good to you?

**Comment by ewels** [comment]
Sounds great!

**Review by MaxUlysse — APPROVED** [review]
Tried it and works well

**Comment by ewels** [comment]
Just waiting on @KevinMenden to be happy now 👍🏻

**Comment by KevinMenden** [comment]
I'm happy, just had this weird error yesterday :thinking:  but that wasn't breaking anything. Just didn't show the log for some reason.
Otherwise it worked like a charm :+1:

**Pull request merged**
