### PR TITLE
Lint check for `System.exit` calls

### PR DESCRIPTION
**Pull request by awgymer**
#1840 for more details

This implements a very simplistic check of all `.nf` and `.groovy` files in the pipeline repo for `System.exit` calls. 

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by awgymer** [comment]
CI is proving this works 😂 
```
╭─ [✗] 6 Pipeline Tests Failed ────────────────────────────────────────────────╮
│                                                                              │
│ system_exit: System.exit in WorkflowTestpipeline.groovy: System.exit(1)      │
│ system_exit: System.exit in WorkflowTestpipeline.groovy: System.exit(1)      │
│ system_exit: System.exit in NfcoreSchema.groovy: System.exit(1)              │
│ system_exit: System.exit in WorkflowMain.groovy: System.exit(0)              │
│ system_exit: System.exit in WorkflowMain.groovy: System.exit(0)              │
│ system_exit: System.exit in WorkflowMain.groovy: System.exit(1)              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by awgymer** [comment]
I _think_ we should allow `System.exit(0)` - replacing it with an error doesn't really make sense and after discussion with @drpatelh it is only used for the `help` and `version` options, to exit cleanly without running.  

cc @ewels as you created the parent issue

**Comment by awgymer** [comment]
Does this need an independent test? It is tested as part of the lint test pipeline?

**Review by mashehu — APPROVED** [review]

**Comment by ewels** [comment]
> I _think_ we should allow `System.exit(0)` - replacing it with an error doesn't really make sense and after discussion with @drpatelh it is only used for the `help` and `version` options, to exit cleanly without running.

I'm still a bit nervous about this. @pditommaso / @bentsherman - are `System.exit(0)` calls when we want to exit cleanly without an error exit code? Or is there a good alternative to `error()` that we can use when there is no error?

**Comment by bentsherman** [comment]
I think the `exit()` method is the standard way to exit with a given exit code: https://github.com/nextflow-io/nextflow/blob/7ce05c15f253059f5981f29ba85d4e16ab0b7620/modules/nextflow/src/main/groovy/nextflow/Nextflow.groovy#L183-L220

But as you can see it just logs an optional message and then calls `System.exit()`

Are you looking for something that calls the usual shutdown logic in the event of a workflow `terminate` or `finish`? I don't think there is a method for that.

**Pull request merged**
