### PR TITLE
Return remote params to remove commands

### LINKED ISSUE #2041: Restore remote options to <modules/subworkflows> remove command
### Description of the bug

Recent updates to <modules/subworkflows> remove got rid of the remote options for the command. 
This has caused it to be impossible to remove non-nf-core components via the command. 

### Command used and terminal output

```console
nf-core modules --git-remote <my-git-url> remove

Pulling from 'nf-core/modules' (https://github.com/nf-core/modules.git)
CRITICAL Nothing installed from nf-core/modules in pipeline
```

### System information

_No response_

### PR DESCRIPTION
**Pull request by awgymer**
Fixes #2041

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by mashehu** [comment]
Trying to add a test for this now. But it is somehow not working. 🤔

**Comment by awgymer** [comment]
> Trying to add a test for this now. But it is somehow not working. 🤔

Which bit is failing?

**Comment by awgymer** [comment]
Weird error in the CI:
```
Command error:
  Skipping 'SAMPLE3_SE_T2.fastq.gz' which didn't exist, or couldn't be read
```

**Comment by mashehu** [comment]
> Weird error in the CI:

Just a hick-up with the test data repo, rerunning the test fixed it (known issue 😞)

**Review by mashehu — APPROVED** [review]

**Pull request merged**
