### PR TITLE
Specify yaml Loader argument

### PR DESCRIPTION
**Pull request by phue**
Since PyYAML 5.1, a warning is thrown when yaml.load() is called without a loader argument.
More info:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Many thanks to contributing to nf-core/tools!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] `CHANGELOG.md` is updated

**Learn more about contributing:** https://github.com/nf-core/tools/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by drpatelh** [comment]
Thanks for fixing this @phue ! Was very annoying.

Travis failing because `CHANGELOG` needs to be updated.

**Comment by phue** [comment]
I also missed some yaml.load() statements in the tests. Will fix later :+1:

**Comment by phue** [comment]
Ok done.
python2 test is failing. I don't understand why :man_shrugging:

**Comment by apeltzer** [comment]
Maybe something that @sven1103 knows most about as one of our python gurus ;-)

**Comment by phue** [comment]
Using yaml.safe_load() seems to fix the issue with python2. This is good to go.

**Pull request merged**
