### PR TITLE
Changes to nf-core pipelines download CLI

### PR DESCRIPTION
**Pull request by MatthiasZepper**
This PR suggests a change to the CLI of `nf-core download` respectively now `nf-core pipelines download`. 

To free the `-p` flag for Seqera Platform, the `-d` flag was needed for `--parallel-downloads` and thus `--download-configs` had to change from `-d` to `-c`.

This is also more consistent, since most short flags use the first letter of the last word as the short flag, e.g. `-l` for `--container-library` or `-u` for `--container-cache-utilisation`.

Furthermore, `-t` / `--tower` has now been entirely removed as it was deprecated before. Therefore `-t` could have been used for `--tag` in the future, but there is hardly a point of having a short flag for a three letter argument, so I refrained from introducing it. 

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] <strike>Documentation in `docs` is updated</strike> _Does that still apply? I looked into the new `docs` folder, but it seems the old manual Markdown was replaced by some autogenerated API documentation: `docs/api/_src/api/pipelines/download.md`_

### CODE REVIEW

**Comment by MatthiasZepper** [comment]
Thanks for taking a look already. There are some more tweaks coming...

> May I ask why `--download-configuration` has changed to yes/no instead of being a flag?

Because I have occasionally received complaints similar to #3043 and the prompt for downloading the configs was one of them. Technically, `if stderr.is_interactive:` should prevent prompts in non-interactive shells, but apparently there are users where this fails. 

I never felt it was a pressing issue, but kept it in the back of my head for the next major version jump.

**Comment by mashehu** [comment]
I would keep it as a flag. Pointing towards the [one-liner approach suggested by @ewels](https://github.com/nf-core/tools/issues/3043#issuecomment-2376682891) should be enough.

**Comment by MatthiasZepper** [comment]
> I would keep it as a flag. Pointing towards the [one-liner approach suggested by @ewels](https://github.com/nf-core/tools/issues/3043#issuecomment-2376682891) should be enough.

But the download configuration prompt and the $NXF_SINGULARITY_CACHEDIR are two different things ?!?

**Comment by mashehu** [comment]
okay, then I misunderstood why you linked the issue... just for clarity's sake: one can add the also the `download-configuration` with `$NFCORE_DOWNLOAD-CONFIGURATION`

**Review by mirpedrol — APPROVED** [review]
LGTM, we are only missing updating the docs for these changes. Is this PR ready to be merged @MatthiasZepper ?

**Comment by MatthiasZepper** [comment]
> just for clarity's sake: one can add the also the `download-configuration` with `$NFCORE_DOWNLOAD-CONFIGURATION`

I did not know that. I also do not find it in the code. So how does that work?
```Python
            if not self.platform and self.include_configs is None:
                self.prompt_config_inclusion()
```
> LGTM, we are only missing updating the docs for these changes. Is this PR ready to be merged @MatthiasZepper ?

From my side, absolutely, since there is seemingly no need to address the CACHE DIR issue, since the OP did never reply. But I do not think that @mashehu is happy with the other changes yet?

**Comment by mashehu** [comment]
the env. variable thing comes with click: https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables

**Pull request merged**
